#!/usr/bin/env python3
import json

# Notebook content for W7 Day 4 - Multi-agent collaboration
notebook_content = {
  "cells": [
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🎯 W7 Day 4 - 多Agent协作模式\n",
        "# 数字员工架构深化 - Multi-Agent System\n",
        "\n",
        "from matplotlib import font_manager\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "import seaborn as sns\n",
        "\n",
        "# 配置中文字体\n",
        "font_path = \"/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc\"\n",
        "font_manager.fontManager.addfont(font_path)\n",
        "font_name = font_manager.FontProperties(fname=font_path).get_name()\n",
        "plt.rcParams[\"font.family\"] = font_name\n",
        "plt.rcParams[\"axes.unicode_minus\"] = False\n",
        "\n",
        "print(\"🎯 使用字体:\", font_name)\n",
        "print(\"📅 日期: 2026-07-16\")\n",
        "print(\"🔥 第7周 - Day 4: 多Agent协作模式\")\n",
        "print(\"\\n\" + \"=\"*80)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🎯 今日学习目标\n",
        "\n",
        "## 核心概念\n",
        "- **协作模式**：主Agent+子Agent、同级Agent协作\n",
        "- **TaskFlow**：多步骤可追踪工作流\n",
        "- **上下文传递**：isolated vs fork的选择策略\n",
        "\n",
        "## 技能关联\n",
        "- 💡 **LangChat Subagent**：主Agent调用子Agent的协作模式\n",
        "- 💡 **Orchestrator路由**：多Agent系统的任务分配和结果聚合\n",
        "- 💡 **商管团队**：商铺、物业、会员的Agent协作架构"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🔄 昨日复习\n",
        "\n",
        "## Day 3：任务编排与工作流\n",
        "\n",
        "### 核心知识点\n",
        "1. **工具编排层次**：单工具→多工具链→自动化工作流\n",
        "   - Level 1：单工具调用\n",
        "   - Level 2：工具链执行\n",
        "   - Level 3：工作流编排\n",
        "   - Level 4：智能编排\n",
        "2. **工作流引擎**：依赖解析、并行执行、错误处理\n",
        "   - 拓扑排序算法\n",
        "   - 任务状态管理\n",
        "   - 容错机制\n",
        "3. **定时任务系统**：Cron表达式、调度策略\n",
        "   - 商业地产定时场景\n",
        "   - 任务优先级管理\n",
        "   - 容错和重试\n",
        "4. **跨平台消息路由**：统一消息处理\n",
        "   - 平台适配策略\n",
        "   - 消息状态追踪\n",
        "   - 广播和路由\n",
        "\n",
        "### 💡 业务关联思考\n",
        "- **LangChat Skill编排**：多个Skill的串联/并行执行形成复杂业务流程\n",
        "- **Orchestrator路由**：system binding下的工具调用链支持多步骤业务处理\n",
        "- **商管工作流**：商铺租赁→收费→运营的自动化流程提升运营效率"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 📊 学习进度可视化\n",
        "weeks = 18\n",
        "completed_weeks = 7\n",
        "current_week = 7\n",
        "current_day = 4\n",
        "\n",
        "fig, ax = plt.subplots(1, 1, figsize=(12, 3))\n",
        "\n",
        "# 绘制进度条\n",
        "for i in range(weeks):\n",
        "    if i < completed_weeks:\n",
        "        color = 'green' if i < current_week - 1 else 'orange'\n",
        "        alpha = 1.0 if i < current_week - 1 else 0.8\n",
        "        ax.barh(0, 1, left=i, height=1, color=color, alpha=alpha, \n",
        "                label=f'W{i+1}' if i == 0 else '')\n",
        "    else:\n",
        "        ax.barh(0, 1, left=i, height=1, color='lightgray', alpha=0.5)\n",
        "\n",
        "# 标记当前位置\n",
        "ax.axvline(x=current_week-1 + current_day/7, color='red', linewidth=3, \n",
        "          label=f'当前: W{current_week}-Day{current_day}')\n",
        "\n",
        "ax.set_xlim(0, weeks)\n",
        "ax.set_ylim(-0.5, 0.5)\n",
        "ax.set_yticks([])\n",
        "ax.set_xlabel('学习进度 (18周)', fontsize=12)\n",
        "ax.set_title('企业AI平台架构师学习进度', fontsize=14, fontweight='bold')\n",
        "ax.legend(loc='upper right', bbox_to_anchor=(1.15, 1))\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f\"🎯 当前进度: 第{current_week}周 - 第{current_day}天\")\n",
        "print(f\"✅ 已完成: {completed_weeks}周\")\n",
        "print(f\"📈 总进度: {completed_weeks/weeks*100:.1f}%\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 📚 今日新知识：多Agent协作模式\n",
        "\n",
        "## 1. 多Agent协作架构\n",
        "\n",
        "### 主Agent + 子Agent模式\n",
        "\n",
        "```mermaid\n",
        "graph TD\n",
        "    A[主Agent] --> B[子Agent 1]\n",
        "    A --> C[子Agent 2]\n",
        "    A --> D[子Agent 3]\n",
        "    B --> E[任务执行器]\n",
        "    C --> F[数据处理]\n",
        "    D --> G[结果整合]\n",
        "    E --> H[结果返回]\n",
        "    F --> H\n",
        "    G --> H\n",
        "```\n",
        "\n",
        "### 协作层次\n",
        "\n",
        "| 层次 | 描述 | 特点 | 适用场景 |\n",
        "|------|------|------|----------|\n",
        "| **主从模式** | 主Agent分配任务给子Agent | 集中式控制、层级管理 | 复杂任务分解 |\n",
        "| **同层级协作** | Agent之间平等协作 | 分布式、对等通信 | 并行任务处理 |\n",
        "| **混合模式** | 主从+同层级结合 | 灵活架构、可扩展 | 大规模协作 |\n",
        "| **联邦模式** | Agent保持独立性 | 数据安全、隐私保护 | 跨组织协作 |"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🤖 多Agent协作系统实现\n",
        "from dataclasses import dataclass\n",
        "from typing import Dict, List, Any, Optional\n",
        "import time\n",
        "import threading\n",
        "from enum import Enum\n",
        "\n",
        "class AgentStatus(Enum):\n",
        "    IDLE = \"idle\"\n",
        "    WORKING = \"working\"\n",
        "    COMPLETED = \"completed\"\n",
        "    FAILED = \"failed\"\n",
n",
        "@dataclass\nclass Agent:\n",
        "    \"\"\"Agent基类\"\"\"\n",
        "    name: str\n",
        "    agent_id: str\n",
        "    capabilities: List[str]\n",
        "    status: AgentStatus = AgentStatus.IDLE\n",
        "    current_task: Optional[str] = None\n",
        "    result: Any = None\n",
        "    error: Optional[str] = None\n",
n",
        "    def execute_task(self, task_data: Dict[str, Any]) -> Any:\n",
        "        \"\"\"执行任务\"\"\"\n",
        "        self.status = AgentStatus.WORKING\n",
        "        self.current_task = task_data.get('task_name')\n",
        "        \n",
        "        try:\n",
        "            print(f\"🔄 {self.name} 开始执行任务: {self.current_task}\")\n",
        "            \n",
        "            # 模拟任务执行\n",
        "            if self.current_task == \"数据收集\":\n",
        "                time.sleep(2)\n",
        "                self.result = {\"data_size\": 1000, \"sources\": [\"数据库\", \"API\", \"文件\"]}\n",
        "            elif self.current_task == \"数据分析\":\n",
        "                time.sleep(3)\n",
        "                self.result = {\"insights\": [\"趋势增长\", \"异常检测\"], \"accuracy\": 0.95}\n",
        "            elif self.current_task == \"报告生成\":\n",
        "                time.sleep(1)\n",
        "                self.result = {\"report_type\": \"PDF\", \"pages\": 10}\n",
        "            else:\n",
        "                self.result = {\"status\": \"success\", \"message\": \"任务完成\"}\n",
n",
        "            self.status = AgentStatus.COMPLETED\n",
        "            print(f\"✅ {self.name} 任务完成: {self.current_task}\")\n",
        "            return self.result\n",
n",
        "        except Exception as e:\n",
        "            self.status = AgentStatus.FAILED\n",
        "            self.error = str(e)\n",
        "            print(f\"❌ {self.name} 任务失败: {self.current_task} - {e}\")\n",
        "            raise\n",
n",
        "    def get_status(self) -> Dict[str, Any]:\n",
        "        \"\"\"获取Agent状态\"\"\"\n",
        "        return {\n",
        "            \"name\": self.name,\n",
        "            \"agent_id\": self.agent_id,\n",
        "            \"status\": self.status.value,\n",
        "            \"current_task\": self.current_task,\n",
        "            \"capabilities\": self.capabilities\n",
        "        }\n",
n",
        "class SubAgent(Agent):\n",
        "    \"\"\"子Agent实现\"\"\"\n",
        "    def __init__(self, name: str, agent_id: str, capabilities: List[str], master_agent=None):\n",
        "        super().__init__(name, agent_id, capabilities)\n",
        "        self.master_agent = master_agent\n",
n",
        "    def report_to_master(self, task_result: Any):\n",
        "        \"\"\"向主Agent报告结果\"\"\"\n",
        "        if self.master_agent:\n",
        "            self.master_agent.receive_subagent_result(self.agent_id, task_result)\n",
n",
        "class MasterAgent(Agent):\n",
        "    \"\"\"主Agent实现\"\"\"\n",
        "    def __init__(self, name: str, agent_id: str):\n",
        "        super().__init__(name, agent_id, [\"任务分配\", \"结果整合\", \"决策制定\"])\n",
        "        self.subagents: Dict[str, SubAgent] = {}\n",
        "        self.task_results: Dict[str, Any] = {}\n",
        "        self.task_queue: List[Dict[str, Any]] = []\n",
n",
        "    def add_subagent(self, subagent: SubAgent):\n",
        "        \"\"\"添加子Agent\"\"\"\n",
        "        self.subagents[subagent.agent_id] = subagent\n",
        "        subagent.master_agent = self\n",
        "        print(f\"📋 主Agent {self.name} 添加子Agent: {subagent.name}\")\n",
n",
        "    def assign_task(self, task: Dict[str, Any]):\n",
        "        \"\"\"分配任务给合适的子Agent\"\"\"\n",
        "        task_name = task.get('task_name')\n",
        "        required_capability = task.get('required_capability')\n",
n",
        "        print(f\"📝 主Agent {self.name} 分配任务: {task_name}\")\n",
n",
        "        # 查找合适的子Agent\n",
        "        available_agents = [agent for agent in self.subagents.values() \n",
        "                          if agent.status == AgentStatus.IDLE and \n",
        "                          required_capability in agent.capabilities]\n",
n",
        "        if not available_agents:\n",
        "            raise ValueError(f\"没有可用的子Agent能够处理任务: {task_name}\")\n",
n",
        "        # 选择第一个可用的Agent\n",
        "        selected_agent = available_agents[0]\n",
        "        \n",
        "        # 异步执行任务\n",
        "        thread = threading.Thread(\n",
        "            target=self._execute_subagent_task,\n",
        "            args=(selected_agent, task)\n",
        "        )\n",
        "        thread.start()\n",
n",
        "        return selected_agent.agent_id\n",
n",
        "    def _execute_subagent_task(self, subagent: SubAgent, task: Dict[str, Any]):\n",
        "        \"\"\"执行子Agent任务\"\"\"\n",
        "        try:\n",
        "            result = subagent.execute_task(task)\n",
        "            self.receive_subagent_result(subagent.agent_id, result)\n",
        "        except Exception as e:\n",
        "            self.receive_subagent_result(subagent.agent_id, None, str(e))\n",
n",
        "    def receive_subagent_result(self, subagent_id: str, result: Any, error: str = None):\n",
        "        \"\"\"接收子Agent结果\"\"\"\n",
        "        self.task_results[subagent_id] = {\n",
        "            'result': result,\n",
        "            'error': error,\n",
        "            'timestamp': time.time()\n",
        "        }\n",
        "        print(f\"📥 主Agent {self.name} 收到子Agent {subagent_id} 的结果\")\n",
n",
        "    def integrate_results(self) -> Dict[str, Any]:\n",
        "        \"\"\"整合所有子Agent的结果\"\"\"\n",
        "        print(f\"🔄 主Agent {self.name} 整合结果...\")\n",
n",
        "        integrated_result = {\n",
        "            'total_subagents': len(self.subagents),\n",
        "            'completed_tasks': 0,\n",
        "            'failed_tasks': 0,\n",
        "            'results': {},\n",
        "            'summary': ''\n",
        "        }\n",
n",
        "        for subagent_id, result_info in self.task_results.items():\n",
        "            if result_info['error']:\n",
        "                integrated_result['failed_tasks'] += 1\n",
        "                integrated_result['results'][subagent_id] = {\n",
        "                    'status': 'failed',\n",
        "                    'error': result_info['error']\n",
        "                }\n",
        "            else:\n",
        "                integrated_result['completed_tasks'] += 1\n",
        "                integrated_result['results'][subagent_id] = {\n",
        "                    'status': 'success',\n",
        "                    'data': result_info['result']\n",
        "                }\n",
n",
        "        # 生成总结\n",
        "        if integrated_result['completed_tasks'] > 0:\n",
        "            accuracy = integrated_result['completed_tasks'] / len(self.subagents)\n",
        "            integrated_result['summary'] = f\"任务完成率: {accuracy*100:.1f}% ({integrated_result['completed_tasks']}/{len(self.subagents)})\"\n",
        "        else:\n",
        "            integrated_result['summary'] = \"所有任务均失败\"\n",
n",
        "        return integrated_result\n",
n",
        "# 创建多Agent系统\n",
        "print(\"🚀 创建多Agent协作系统...\")\n",
n",
        "# 创建主Agent\n",
        "master_agent = MasterAgent(\"智能主控\", \"master-001\")\n",
n",
        "# 创建子Agent\n",
        "data_agent = SubAgent(\"数据收集专家\", \"data-001\", [\"数据收集\", \"API调用\"], master_agent)\n",
        "analysis_agent = SubAgent(\"数据分析专家\", \"analysis-001\", [\"数据分析\", \"机器学习\"], master_agent)\n",
        "report_agent = SubAgent(\"报告生成专家\", \"report-001\", [\"报告生成\", \"文档处理\"], master_agent)\n",
n",
        "# 添加子Agent到主Agent\n",
        "master_agent.add_subagent(data_agent)\n",
        "master_agent.add_subagent(analysis_agent)\n",
        "master_agent.add_subagent(report_agent)\n",
n",
        "# 查看初始状态\n",
        "print(\"\\n📊 Agent初始状态:\")\n",
        "for agent_id, agent in master_agent.subagents.items():\n",
        "    print(f\"  {agent.get_status()}\")\n",
n",
        "# 执行协作任务\n",
        "print(\"\\n🔄 开始协作任务...\")\n",
        "\n",
        "task1 = {\"task_name\": \"数据收集\", \"required_capability\": \"数据收集\"}\n",
        "task2 = {\"task_name\": \"数据分析\", \"required_capability\": \"数据分析\"}\n",
        "task3 = {\"task_name\": \"报告生成\", \"required_capability\": \"报告生成\"}\n",
n",
        "# 分配任务\n",
        "agent1_id = master_agent.assign_task(task1)\n",
        "agent2_id = master_agent.assign_task(task2)\n",
        "agent3_id = master_agent.assign_task(task3)\n",
n",
        "# 等待所有任务完成\n",
        "time.sleep(5)\n",
n",
        "# 整合结果\n",
        "final_result = master_agent.integrate_results()\n",
        "print(\"\\n🎯 最终整合结果:\")\n",
        "print(f\"  {final_result}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 2. TaskFlow多步骤可追踪工作流\n",
        "\n",
        "### TaskFlow架构设计\n",
        "\n",
        "```mermaid\n",
        "graph LR\n",
        "    A[Task启动] --> B[任务分解]\n",
        "    B --> C[Agent分配]\n",
        "    C --> D[任务执行]\n",
        "    D --> E[状态监控]\n",
        "    E --> F[结果收集]\n",
        "    F --> G[错误处理]\n",
        "    G --> H[结果整合]\n",
        "    H --> I[任务完成]\n",
        "```\n",
        "\n",
        "### TaskFlow核心特性\n",
n",
        "- **任务可追踪**：每个步骤都有完整的状态记录\n",
        "- **错误恢复**：支持任务失败后的自动重试和恢复\n",
        "- **并行执行**：支持多个Agent同时工作\n",
        "- **动态调度**：根据Agent负载动态分配任务\n",
        "- **结果聚合**：智能整合多个Agent的执行结果"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🔄 TaskFlow多步骤工作流实现\n",
        "import uuid\n",
        "from datetime import datetime\n",
        "from typing import List, Dict, Any, Callable\n",
        "\n",
        "@dataclass\nclass TaskStep:\n",
        "    \"\"\"任务步骤\"\"\"\n",
        "    step_id: str\n",
        "    name: str\n",
        "    description: str\n",
        "    execute_func: Callable\n",
        "    dependencies: List[str] = None\n",
        "    status: str = \"pending\"\n",
        "    result: Any = None\n",
        "    error: str = None\n",
        "    start_time: datetime = None\n",
        "    end_time: datetime = None\n",
        "    assigned_agent: str = None\n",
n",
        "class TaskFlow:\n",
        "    \"\"\"TaskFlow工作流引擎\"\"\"\n",
        "    def __init__(self, name: str):\n",
        "        self.name = name\n",
        "        self.steps: Dict[str, TaskStep] = {}\n",
        "        self.execution_order: List[str] = []\n",
        "        self.context: Dict[str, Any] = {}\n",
        "        self.agent_pool: Dict[str, Agent] = {}\n",
        "        self.max_retries = 3\n",
        "        self.retry_delay = 1\n",
n",
        "    def add_step(self, step: TaskStep):\n",
        "        \"\"\"添加步骤到工作流\"\"\"\n",
        "        self.steps[step.step_id] = step\n",
        "        print(f\"📝 添加工作流步骤: {step.name}\")\n",
n",
        "    def add_agent(self, agent: Agent):\n",
        "        \"\"\"添加Agent到执行池\"\"\"\n",
        "        self.agent_pool[agent.agent_id] = agent\n",
        "        print(f\"🤖 添加Agent到池: {agent.name} ({agent.agent_id})\")\n",
n",
        "    def _resolve_dependencies(self) -> List[str]:\n",
        "        \"\"\"解析步骤依赖关系，返回执行顺序\"\"\"\n",
        "        # 拓扑排序\n",
        "        in_degree = {}\n",
        "        graph = {}\n",
        "        \n",
        "        # 初始化\n",
        "        for step_id, step in self.steps.items():\n",
        "            in_degree[step_id] = len(step.dependencies) if step.dependencies else 0\n",
        "            graph[step_id] = step.dependencies if step.dependencies else []\n",
        "        \n",
        "        # 找到入度为0的步骤\n",
        "        queue = [step_id for step_id, degree in in_degree.items() if degree == 0]\n",
        "        execution_order = []\n",
        "        \n",
        "        while queue:\n",
        "            step_id = queue.pop(0)\n",
        "            execution_order.append(step_id)\n",
        "            \n",
        "            # 更新依赖步骤的入度\n",
        "            for dep_step_id in graph[step_id]:\n",
        "                in_degree[dep_step_id] -= 1\n",
        "                if in_degree[dep_step_id] == 0:\n",
        "                    queue.append(dep_step_id)\n",
        "        \n",
        "        if len(execution_order) != len(self.steps):\n",
        "            raise ValueError(\"工作流存在循环依赖\")\n",
        "        \n",
        "        return execution_order\n",
n",
        "    def _select_best_agent(self, required_capability: str) -> Optional[Agent]:\n",
        "        \"\"\"选择最适合执行任务的Agent\"\"\"\n",
        "        available_agents = [agent for agent in self.agent_pool.values() \n",
        "                          if agent.status == AgentStatus.IDLE and \n",
        "                          required_capability in agent.capabilities]\n",
        "        \n",
        "        if not available_agents:\n",
        "            return None\n",
        "        \n",
        "        # 简单策略：选择第一个可用的Agent\n",
        "        # 实际应用中可以根据负载、性能等因素选择\n",
        "        return available_agents[0]\n",
n",
        "    def _execute_step_with_retry(self, step: TaskStep) -> bool:\n",
        "        \"\"\"执行步骤，支持重试\"\"\"\n",
        "        for attempt in range(self.max_retries):\n",
        "            try:\n",
        "                print(f\"🔄 执行步骤 {step.name} (尝试 {attempt + 1}/{self.max_retries})\")\n",
        "                \n",
        "                # 检查依赖是否满足\n",
        "                if step.dependencies:\n",
        "                    for dep_step_id in step.dependencies:\n",
        "                        if dep_step_id not in self.context:\n",
        "                            raise ValueError(f\"依赖步骤 {dep_step_id} 未完成\")\n",
n",
        "                # 选择Agent执行\n",
        "                required_capability = step.name  # 简化：步骤名作为能力要求\n",
        "                agent = self._select_best_agent(required_capability)\n",
        "                \n",
        "                if not agent:\n",
        "                    raise ValueError(f\"没有可用的Agent能够处理: {step.name}\")\n",
n",
        "                # 分配任务\n",
        "                step.assigned_agent = agent.agent_id\n",
        "                agent.status = AgentStatus.WORKING\n",
        "                step.start_time = datetime.now()\n",
n",
        "                # 执行步骤\n",
        "                step.result = step.execute_func(self.context)\n",
        "                step.status = \"completed\"\n",
        "                step.end_time = datetime.now()\n",
        "                \n",
        "                # 更新Agent状态\n",
        "                agent.status = AgentStatus.COMPLETED\n",
        "                agent.current_task = None\n",
        "                \n",
        "                # 保存结果到上下文\n",
        "                self.context[step.step_id] = step.result\n",
        "                \n",
        "                print(f\"✅ 步骤 {step.name} 完成\")\n",
        "                return True\n",
n",
        "            except Exception as e:\n",
        "                step.status = \"failed\"\n",
        "                step.error = str(e)\n",
        "                print(f\"❌ 步骤 {step.name} 失败: {e}\")\n",
        "                \n",
        "                if attempt < self.max_retries - 1:\n",
        "                    print(f\"⏳ 等待 {self.retry_delay} 秒后重试...\")\n",
        "                    time.sleep(self.retry_delay)\n",
        "                \n",
        "        return False\n",
n",
        "    def execute(self) -> Dict[str, Any]:\n",
        "        \"\"\"执行整个工作流\"\"\"\n",
        "        print(f\"🚀 开始执行工作流: {self.name}\")\n",
        "        \n",
        "        # 解析依赖关系\n",
        "        self.execution_order = self._resolve_dependencies()\n",
        "        print(f\"📋 执行顺序: {' → '.join(self.execution_order)}\")\n",
        "        \n",
        "        # 执行步骤\n",
        "        completed_steps = 0\n",
        "        failed_steps = 0\n",
        "        \n",
        "        for step_id in self.execution_order:\n",
        "            step = self.steps[step_id]\n",
        "            \n",
        "            if self._execute_step_with_retry(step):\n",
        "                completed_steps += 1\n",
        "            else:\n",
        "                failed_steps += 1\n",
        "                \n",
        "                # 如果关键步骤失败，停止工作流\n",
        "                if step.status == \"critical\":\n",
        "                    print(f\"⚠️ 关键步骤 {step.name} 失败，停止工作流\")\n",
        "                    break\n",
n",
        "        # 生成执行报告\n",
        "        report = {\n",
        "            \"workflow_name\": self.name,\n",
        "            \"total_steps\": len(self.steps),\n",
        "            \"completed_steps\": completed_steps,\n",
        "            \"failed_steps\": failed_steps,\n",
        "            \"success_rate\": completed_steps / len(self.steps) if self.steps else 0,\n",
        "            \"execution_order\": self.execution_order,\n",
        "            \"step_details\": {step_id: {\n",
        "                \"name\": step.name,\n",
        "                \"status\": step.status,\n",
        "                \"assigned_agent\": step.assigned_agent,\n",
        "                \"duration\": (step.end_time - step.start_time).total_seconds() if step.start_time and step.end_time else None,\n",
        "                \"error\": step.error\n",
        "            } for step_id, step in self.steps.items()}\n",
        "        }\n",
n",
        "        print(f\"🎉 工作流执行完成: {completed_steps}/{len(self.steps)} 步骤成功\")\n",
        "        return report\n",
n",
        "# 创建TaskFlow工作流示例\n",
        "print(\"🚀 创建TaskFlow工作流...\")\n",
n",
        "# 创建工作流\n",
        "workflow = TaskFlow(\"商铺数据分析工作流\")\n",
n",
        "# 创建步骤\n",
        "def data_collection(context):\n",
        "    \"\"\"数据收集步骤\"\"\"\n",
        "    print(\"📊 收集商铺销售数据...\")\n",
        "    time.sleep(1)\n",
        "    return {\"sales_data\": [2500, 2800, 3200, 2900], \"date_range\": \"2026-07-01 to 2026-07-15\"}\n",
n",
        "def data_analysis(context):\n",
        "    \"\"\"数据分析步骤\"\"\"\n",
        "    sales_data = context.get(\"data_collection\", {}).get(\"sales_data\", [])\n",
        "    print(\"📈 分析销售趋势...\")\n",
        "    time.sleep(2)\n",
        "    avg_sales = sum(sales_data) / len(sales_data) if sales_data else 0\n",
        "    return {\"avg_sales\": avg_sales, \"trend\": \"increasing\", \"accuracy\": 0.92}\n",
n",
        "def report_generation(context):\n",
        "    \"\"\"报告生成步骤\"\"\"\n",
        "    analysis = context.get(\"data_analysis\", {})\n",
        "    print(\"📄 生成分析报告...\")\n",
        "    time.sleep(1)\n",
        "    return {\"report_type\": \"PDF\", \"pages\": 8, \"summary\": f\"平均销售额: {analysis.get('avg_sales', 0):.0f}\"}\n",
n",
        "def notification(context):\n",
        "    \"\"\"通知推送步骤\"\"\"\n",
        "    report = context.get(\"report_generation\", {})\n",
        "    print(\"📱 推送通知给商铺业主...\")\n",
        "    time.sleep(1)\n",
        "    return {\"notification_sent\": True, \"recipients\": [\"商铺业主\"], \"delivery_method\": \"微信\"}\n",
n",
        "# 添加步骤到工作流（依赖关系）\n",
        "workflow.add_step(TaskStep(\"data_collection\", \"数据收集\", \"收集商铺销售数据\", data_collection))\n",
        "workflow.add_step(TaskStep(\"data_analysis\", \"数据分析\", \"分析销售数据趋势\", data_analysis, [\"data_collection\"]))\n",
        "workflow.add_step(TaskStep(\"report_generation\", \"报告生成\", \"生成分析报告\", report_generation, [\"data_analysis\"]))\n",
        "workflow.add_step(TaskStep(\"notification\", \"通知推送\", \"推送分析结果\", notification, [\"report_generation\"]))\n",
n",
        "# 添加Agent到工作流\n",
        "workflow.add_agent(data_agent)\n",
        "workflow.add_agent(analysis_agent)\n",
        "workflow.add_agent(report_agent)\n",
n",
        "# 添加一个专门的通知Agent\n",
        "notification_agent = SubAgent(\"通知专家\", \"notify-001\", [\"通知推送\"], master_agent)\n",
        "workflow.add_agent(notification_agent)\n",
n",
        "# 执行工作流\n",
        "print(\"\\n🔄 开始执行商铺数据分析工作流...\")\n",
        "result = workflow.execute()\n",
        "print(f\"\\n📊 工作流执行结果: {result}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 3. 上下文传递策略\n",
        "\n",
        "### isolated vs fork 的选择策略\n",
        "\n",
        "#### isolated 模式\n",
        "```\n",
        "主Agent → 子Agent\n",
        "    ↓\n",
        "全新上下文\n",
        "    ↓\n",
        "独立执行\n",
        "    ↓\n",
        "结果返回\n",
        "```\n",
        "\n",
        "**特点：**\n",
        "- ✅ 隔离性好，避免上下文污染\n",
        "- ✅ 内存使用可控\n",
        "- ❌ 需要重新传递所有必要信息\n",
        "- ❌ 无法利用历史对话上下文\n",
        "\n",
        "**适用场景：**\n",
        "- 独立任务执行\n",
        "- 安全要求高的场景\n",
        "- 资源受限环境\n",
        "\n",
        "#### fork 模式\n",
        "```\n",
        "主Agent → 子Agent\n",
        "    ↓\n",
        "复制上下文\n",
        "    ↓\n",
        "共享历史\n",
        "    ↓\n",
        "上下文延续\n",
        "```\n",
        "\n",
        "**特点：**\n",
        "- ✅ 保持对话连续性\n",
        "- ✅ 无需重复传递历史\n",
        "- ❌ 内存消耗较大\n",
        "- ❌ 可能存在上下文污染\n",
        "\n",
        "**适用场景：**\n",
        "- 复杂对话场景\n",
        "- 需要历史上下文\n",
        "- 长时间协作任务"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🔄 上下文传递策略实现\n",
        "import uuid\n",
        "from datetime import datetime\n",
        "from dataclasses import dataclass\n",
        "from typing import Dict, Any, List\n",
        "\n",
        "@dataclass\nclass ContextData:\n",
        "    \"\"\"上下文数据结构\"\"\"\n",
        "    session_id: str\n",
        "    user_id: str\n",
        "    conversation_history: List[Dict[str, Any]]\n",
        "    current_task: Dict[str, Any]\n",
        "    created_at: datetime\n",
        "    metadata: Dict[str, Any] = None\n",
n",
        "class ContextManager:\n",
        "    \"\"\"上下文管理器\"\"\"\n",
        "    def __init__(self):\n",
        "        self.contexts: Dict[str, ContextData] = {}\n",
        "        self.max_history = 10  # 最大历史记录数\n",
n",
        "    def create_isolated_context(self, user_id: str, task_requirements: Dict[str, Any]) -> str:\n",
        "        \"\"\"创建隔离上下文\"\"\"\n",
        "        session_id = f\"isolated_{uuid.uuid4().hex[:8]}\"\n",
        "        \n",
        "        context = ContextData(\n",
        "            session_id=session_id,\n",
        "            user_id=user_id,\n",
        "            conversation_history=[],  # 隔离模式不传递历史\n",
        "            current_task=task_requirements,\n",
        "            created_at=datetime.now(),\n",
        "            metadata={\"strategy\": \"isolated\", \"original_session\": None}\n",
        "        )\n",
n",
        "        self.contexts[session_id] = context\n",
        "        print(f\"🔒 创建隔离上下文: {session_id}\")\n",
        "        return session_id\n",
n",
        "    def create_forked_context(self, original_session_id: str) -> str:\n",
        "        \"\"\"创建fork上下文\"\"\"\n",
        "        if original_session_id not in self.contexts:\n",
        "            raise ValueError(f\"原始上下文不存在: {original_session_id}\")\n",
n",
        "        original_context = self.contexts[original_session_id]\n",
        "        session_id = f\"fork_{uuid.uuid4().hex[:8]}\"\n",
n",
        "        # 复制历史记录，但限制数量\n",
        "        history = original_context.conversation_history[-self.max_history:]\n",
n",
        "        context = ContextData(\n",
        "            session_id=session_id,\n",
        "            user_id=original_context.user_id,\n",
        "            conversation_history=history,\n",
        "            current_task=original_context.current_task,\n",
        "            created_at=datetime.now(),\n",
        "            metadata={\"strategy\": \"fork\", \"original_session\": original_session_id}\n",
        "        )\n",
n",
        "        self.contexts[session_id] = context\n",
        "        print(f\"🔄 创建fork上下文: {session_id} (来自 {original_session_id})\")\n",
        "        return session_id\n",
n",
        "    def add_conversation(self, session_id: str, message: Dict[str, Any]):\n",
        "        \"\"\"添加对话记录\"\"\"\n",
        "        if session_id not in self.contexts:\n",
        "            raise ValueError(f\"上下文不存在: {session_id}\")\n",
n",
        "        context = self.contexts[session_id]\n",
        "        context.conversation_history.append(message)\n",
n",
        "        # 限制历史记录数量\n",
        "        if len(context.conversation_history) > self.max_history:\n",
        "            context.conversation_history = context.conversation_history[-self.max_history:]\n",
n",
        "    def get_context(self, session_id: str) -> ContextData:\n",
        "        \"\"\"获取上下文\"\"\"\n",
        "        return self.contexts.get(session_id)\n",
n",
        "    def merge_contexts(self, original_session_id: str, fork_session_id: str):\n",
        "        \"\"\"合并fork回原始上下文\"\"\"\n",
        "        if original_session_id not in self.contexts or fork_session_id not in self.contexts:\n",
        "            raise ValueError(\"上下文不存在\")\n",
n",
        "        original_context = self.contexts[original_session_id]\n",
        "        fork_context = self.contexts[fork_session_id]\n",
n",
        "        # 合并对话历史\n",
        "        for message in fork_context.conversation_history:\n",
        "            if message not in original_context.conversation_history:\n",
        "                original_context.conversation_history.append(message)\n",
n",
        "        # 更新当前任务\n",
        "        original_context.current_task.update(fork_context.current_task)\n",
n",
        "        print(f\"📝 合并上下文: {fork_session_id} → {original_session_id}\")\n",
n",
        "        # 清理fork上下文\n",
        "        del self.contexts[fork_session_id]\n",
n",
        "    def auto_select_strategy(self, user_id: str, task_requirements: Dict[str, Any], \n",
        "                           has_history: bool = True) -> str:\n",
        "        \"\"\"自动选择上下文策略\"\"\"\n",
        "        # 基于任务复杂度决定策略\n",
        "        task_complexity = self._calculate_task_complexity(task_requirements)\n",
        "        \n",
        "        if task_complexity > 7 or has_history:\n",
        "            # 复杂任务或有历史，使用fork模式\n",
        "            # 先查找是否有现有上下文\n",
        "            existing_session = self._find_existing_context(user_id)\n",
        "            if existing_session:\n",
        "                return self.create_forked_context(existing_session)\n",
        "            else:\n",
        "                # 创建新上下文，但保留fork策略\n",
        "                session_id = f\"fork_{uuid.uuid4().hex[:8]}\"\n",
        "                context = ContextData(\n",
        "                    session_id=session_id,\n",
        "                    user_id=user_id,\n",
        "                    conversation_history=[],\n",
        "                    current_task=task_requirements,\n",
        "                    created_at=datetime.now(),\n",
        "                    metadata={\"strategy\": \"fork\", \"reason\": \"complex_task\"}\n",
        "                )\n",
        "                self.contexts[session_id] = context\n",
        "                return session_id\n",
        "        else:\n",
        "            # 简单任务，使用isolated模式\n",
        "            return self.create_isolated_context(user_id, task_requirements)\n",
n",
        "    def _calculate_task_complexity(self, task_requirements: Dict[str, Any]) -> int:\n",
        "        \"\"\"计算任务复杂度\"\"\"\n",
        "        complexity = 1  # 基础复杂度\n",
        "        \n",
        "        # 根据任务特征增加复杂度\n",
        "        if task_requirements.get(\"steps\", 0) > 3:\n",
        "            complexity += 2\n",
        "        if len(task_requirements.get(\"tools\", [])) > 2:\n",
        "            complexity += 2\n",
        "        if task_requirements.get(\"requires_memory\", False):\n",
        "            complexity += 1\n",
        "        if task_requirements.get(\"needs_reasoning\", False):\n",
        "            complexity += 2\n",
n",
        "        return min(complexity, 10)  # 最大复杂度10\n",
n",
        "    def _find_existing_context(self, user_id: str) -> Optional[str]:\n",
        "        \"\"\"查找用户的现有上下文\"\"\"\n",
        "        for session_id, context in self.contexts.items():\n",
        "            if context.user_id == user_id and context.metadata.get(\"strategy\") == \"fork\":\n",
        "                return session_id\n",
        "        return None\n",
n",
        "    def cleanup_old_contexts(self, max_age_hours: int = 24):\n",
        "        \"\"\"清理过期上下文\"\"\"\n",
        "        current_time = datetime.now()\n",
        "        to_remove = []\n",
n",
        "        for session_id, context in self.contexts.items():\n",
        "            age = (current_time - context.created_at).total_seconds() / 3600\n",
        "            if age > max_age_hours:\n",
        "                to_remove.append(session_id)\n",
n",
        "        for session_id in to_remove:\n",
        "            del self.contexts[session_id]\n",
        "            print(f\"🗑️ 清理过期上下文: {session_id}\")\n",
n",
        "# 上下文管理器示例\n",
        "print(\"🔄 上下文管理器示例...\")\n",
        "context_manager = ContextManager()\n",
n",
        "# 用户1创建简单任务（isolated模式）\n",
        "simple_task = {\n",
        "    \"task_name\": \"查询天气\",\n",
        "    \"complexity\": 2,\n",
        "    \"steps\": 1,\n",
        "    \"tools\": []\n",
        "}\n",
        "user1_session = context_manager.auto_select_strategy(\"user1\", simple_task, has_history=False)\n",
        "print(f\"用户1简单任务会话: {user1_session} (策略: isolated)\")\n",
n",
        "# 用户1创建复杂任务（fork模式）\n",
        "complex_task = {\n",
        "    \"task_name\": \"商铺经营分析\",\n",
        "    \"complexity\": 8,\n",
        "    \"steps\": 5,\n",
        "    \"tools\": [\"数据分析\", \"报告生成\", \"通知推送\"],\n",
        "    \"requires_memory\": True,\n",
        "    \"needs_reasoning\": True\n",
        "}\n",
        "user1_complex_session = context_manager.auto_select_strategy(\"user1\", complex_task, has_history=True)\n",
        "print(f\"用户1复杂任务会话: {user1_complex_session} (策略: fork)\")\n",
n",
        "# 添加一些对话历史\n",
        "context_manager.add_conversation(user1_complex_session, {\n",
        "    \"role\": \"user\",\n",
        "    \"content\": \"我想分析美华糖水店最近一个月的经营情况\",\n",
        "    \"timestamp\": datetime.now().isoformat()\n",
        "})\n",
n",
        "context_manager.add_conversation(user1_complex_session, {\n",
        "    \"role\": \"assistant\",\n",
        "    \"content\": \"好的，我来帮你收集和分析销售数据\",\n",
        "    \"timestamp\": datetime.now().isoformat()\n",
        "})\n",
n",
        "# 用户2创建简单任务\n",
        "user2_task = {\n",
        "    \"task_name\": \"计算营业额\",\n",
        "    \"complexity\": 3,\n",
        "    \"steps\": 2,\n",
        "    \"tools\": []\n",
        "}\n",
        "user2_session = context_manager.auto_select_strategy(\"user2\", user2_task, has_history=False)\n",
        "print(f\"用户2简单任务会话: {user2_session} (策略: isolated)\")\n",
n",
        "# 查看上下文状态\n",
        "print(\"\\n📊 当前上下文状态:\")\n",
        "for session_id, context in context_manager.contexts.items():\n",
        "    print(f\"  {session_id}: {context.metadata}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🔑 今日英文术语\n",
        "\n",
        "| 术语 | 音标 | 中文含义 | 应用场景 |\n",
        "|------|------|----------|----------|\n",
        "| **Multi-Agent** | /ˈmʌlti.eɪ.dʒənt/ | 多智能体系统 | 协同工作、分布式决策 |\n",
        "| **Collaboration** | /kəˌlæb.əˈreɪ.ʃən/ | 协作 | 团队合作、任务分解 |\n",
        "| **Orchestration** | /ˌɔːr.kɪˈstreɪ.ʃən/ | 编排 | 多Agent任务调度 |\n",
        "| **TaskFlow** | /ˈtæsk.fləʊ/ | 任务流 | 多步骤工作流管理 |\n",
        "| **Subagent** | /ˈsʌb.eɪ.dʒənt/ | 子代理 | 专门化任务处理 |\n",
        "| **Context** | /ˈkɒn.tekst/ | 上下文 | 对话历史、任务状态 |\n",
        "| **Isolation** | /ˌaɪ.səˈleɪ.ʃən/ | 隔离 | 独立执行、安全隔离 |\n",
        "| **Forking** | /ˈfɔː.kɪŋ/ | 分叉 | 上下文复制、并行处理 |\n",
        "| **Workflow** | /ˈwɜːk.fləʊ/ | 工作流 | 业务流程自动化 |\n",
        "| **Synchronization** | /ˌɪŋ.krəʊ.naɪˈzeɪ.ʃən/ | 同步 | 并发任务协调 |"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🎬 推荐学习资源\n",
        "\n",
        "## 视频教程\n",
        "\n",
        "### 1. 【解锁Multi‑Agent世界】大模型如何协同工作\n",
        "- **平台**: B站\n",
        "- **链接**: https://www.bilibili.com/video/BV1bUGnzWEBf/\n",
        "- **内容**: 大模型协同工作原理、自动化完成数据分析到报告生成\n",
        "- **时长**: 约45分钟\n",
        "- **适合**: 理解多Agent协同工作的基本概念\n",
        "\n",
        "### 2. 【一个Tailscale，怎么让多台AI Agent协同工作？】\n",
        "- **平台**: B站\n",
        "- **链接**: https://www.bilibili.com/video/BV1QiNv6AE2i/\n",
        "- **内容**: 多台AI Agent的实际协同部署和配置\n",
        "- **时长**: 约30分钟\n",
        "- **适合**: 了解实际部署和配置细节\n",
        "\n",
        "## 文章阅读\n",
        "\n",
        "### 1. 【多Agent协同开发指南】\n",
        "- **平台**: 知乎\n",
        "- **链接**: https://zhuanlan.zhihu.com/p/2018265716139237578\n",
        "- **内容**: 大语言模型多Agent协同开发技术栈、架构模式、核心框架\n",
        "- **字数**: 约5000字\n",
        "- **亮点**: 系统性介绍多Agent开发技术栈\n",
        "\n",
        "### 2. 【2026年AI Agent编排工具终极指南】\n",
        "- **平台**: 掘金\n",
        "- **链接**: 待确认\n",
        "- **内容**: 12个多Agent协作平台对比、团队协作实战\n",
        "- **字数**: 约8000字\n",
        "- **亮点**: 包含实际平台对比和选择指南"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# ✏️ 课堂练习\n",
        "\n",
        "## 练习1：设计商铺管理多Agent系统\n",
        "\n",
        "### 任务描述\n",
        "设计一个商铺管理系统的多Agent架构，包括：\n",
        "1. 租赁管理Agent\n",
        "2. 财务管理Agent\n",
        "3. 客户服务Agent\n",
        "4. 数据分析Agent\n",
        "5. 系统协调主Agent\n",
        "\n",
        "### 要求\n",
        "- 实现主Agent+子Agent的协作模式\n",
        "- 定义各Agent的能力和职责\n",
        "- 设计任务分配和结果整合机制\n",
        "- 实现错误处理和重试策略\n",
        "\n",
        "```python\n",
        "# 练习1实现\n",
        "class ShopManagementSystem:\n",
        "    def __init__(self):\n",
        "        # 请实现商铺管理多Agent系统\n",
        "        pass\n",
n",
        "    def process_rental_request(self, request):\n",
        "        \"\"\"处理租赁申请\"\"\"\n",
        "        pass\n",
n",
        "    def integrate_financial_data(self, financial_info):\n",
        "        \"\"\"整合财务数据\"\"\"\n",
        "        pass"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 练习2：实现TaskFlow工作流引擎\n",
        "\n",
        "### 任务描述\n",
        "实现一个完整的TaskFlow工作流引擎，支持：\n",
        "1. 任务分解和依赖管理\n",
        "2. Agent动态分配\n",
        "3. 执行状态监控\n",
        "4. 结果智能聚合\n",
        "5. 异常处理和恢复\n",
        "\n",
        "### 要求\n",
        "- 实现步骤的依赖解析算法\n",
        "- 设计Agent负载均衡策略\n",
        "- 添加执行超时和重试机制\n",
        "- 提供详细的执行报告\n",
        "\n",
        "```python\n",
        "# 练习2实现\n",
        "class AdvancedTaskFlow:\n",
        "    def __init__(self):\n",
        "        # 请实现高级TaskFlow工作流引擎\n",
        "        pass\n",
n",
        "    def execute_with_monitoring(self, task):\n",
        "        \"\"\"带监控的任务执行\"\"\"\n",
        "        pass\n",
n",
        "    def handle_failure(self, failed_step):\n",
        "        \"\"\"处理失败步骤\"\"\"\n",
        "        pass"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 📝 课后测试\n",
        "\n",
        "## 测试题\n",
        "\n",
        "### 1. 多Agent协作架构\n",
        "```python\n",
        "问题：实现一个多Agent文档生成系统，包含：\n",
        "- 内容收集Agent\n",
        "- 内容整理Agent\n",
        "- 格式化Agent\n",
        "- 质量检查Agent\n",
        "- 主控Agent\n",
        "\n",
        "要求：\n",
n",
        "1. 设计主Agent+子Agent的协作流程\n",
n",
        "2. 实现任务分配机制\n",
n",
        "3. 添加结果整合功能\n",
n",
        "4. 包含错误处理和重试机制\n",
        "```\n",
        "\n",
        "**考察点**：Agent协作设计、任务分配策略、结果整合算法\n",
        "\n",
        "### 2. TaskFlow工作流\n",
        "\n",
        "**问题**：设计一个商铺营销活动的TaskFlow，包含以下步骤：\n",
n",
        "1. 目标分析\n",
n",
        "2. 策略制定\n",
n",
        "3. 内容创作\n",
n",
        "4. 渠道分发\n",
n",
        "5. 效果追踪\n",
n",
        "6. 优化调整\n",
        "\n",
        "要求：\n",
n",
        "- 使用拓扑排序确保正确的执行顺序\n",
n",
        "- 实现步骤间的数据传递\n",
n",
        "- 添加并行执行支持\n",
n",
        "- 包含执行状态监控\n",
        "\n",
        "```python\n",
n",
        "def create_marketing_workflow():\n",
n",
        "    # 请实现营销活动工作流\n",
n",
        "    pass"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 3. 上下文传递策略\n",
        "\n",
        "**问题**：比较isolated和fork两种上下文传递策略的优缺点，并设计一个自适应策略。\n",
        "\n",
        **要求**: 
        - 分析两种策略的适用场景
        - 设计基于任务特征的自动选择算法
        - 实现上下文合并机制
        - 考虑内存使用和执行效率的平衡\n",
        "\n",
        "```python\n",
        "class AdaptiveContextStrategy:\n",
        "    def __init__(self):\n",
        "        # 请实现自适应上下文策略\n",
        "        pass\n",
n",
        "    def select_strategy(self, task_complexity, history_length):\n",
        "        \"\"\"选择合适的上下文策略\"\"\"\n",
        "        pass\n",
n",
        "    def merge_contexts(self, original_context, fork_context):\n",
        "        \"\"\"合并上下文\"\"\"\n",
        "        pass"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🔄 往期回顾\n",
        "\n",
        "## W1-W7 关键能力串联\n",
        "\n",
        "### **基础层**\n",
        "- **W1**: Transformer架构 → 理解模型基础\n",
        "- **W2**: 大模型训练 → 掌握微调技术\n",
        "- **W3**: RAG知识增强 → 构建Agent知识库\n",
        "- **W4**: 推理优化 → 提升Agent思维能力\n",
        "- **W5**: Agent架构 → 设计数字员工框架\n",
        "- **W6**: Agent实战 → 搭建Function Calling系统\n",
        "\n",
        "### **W7 当前层**\n",
        "- **Day 1**: 数字员工总览 → 行为设计\n",
        "- **Day 2**: 长期记忆 → 语义检索\n",
        "- **Day 3**: 任务编排 → 工作流引擎\n",
        "- **Day 4**: 多Agent协作模式 ⭐(今日)\n",
        "- **Day 5**: 评估体系\n",
        "\n",
        "## 能力图谱\n",
        "\n",
        "```mermaid\n",
        "graph TD\n",
        "    A[基础模型] --> B[知识增强]\n",
        "    B --> C[推理优化]\n",
        "    C --> D[Agent架构]\n",
        "    D --> E[长期记忆]\n",
        "    E --> F[任务编排]\n",
        "    F --> G[多Agent协作]\n",
        "    G --> H[评估体系]\n",
        "    G --> I[LangChat Runtime]\n",
        "    H --> J[Orchestrator Quality]\n",
        "```\n",
        "\n",
        "### 💡 能力关联思考\n",
        "\n",
        1. **多Agent协作**是系统复杂度的重要里程碑\n",
        "   - 从单个Agent的"个人能力"提升到团队的"协同能力"\n",
        "   - 支持大规模、复杂业务场景的自动化处理\n",
        "\n",
        2. **TaskFlow**提供了多Agent协作的执行框架\n",
        "   - 将复杂任务分解为可管理的子任务\n",
        "   - 支持并行执行和智能调度\n",
        "\n",
        3. **上下文策略**影响协作效果的关键因素\n",
        "   - isolated确保任务隔离性\n",
        "   - fork保持对话连续性\n",
        "   - 自适应策略根据任务特征自动选择"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🎯 今日总结\n",
        "\n",
        "## 核心收获\n",
        "\n",
        1. **多Agent协作模式**：主Agent+子Agent、同级Agent协作\n",
        "   - 主从模式：集中式控制、层级管理\n",
        "   - 同层级协作：分布式、对等通信\n",
        "   - 混合模式：灵活架构、可扩展\n",
        "   - 联邦模式：数据安全、隐私保护\n",
        "\n",
        2. **TaskFlow工作流引擎**：多步骤可追踪执行\n",
        "   - 任务分解和依赖管理\n",
        "   - Agent动态分配\n",
        "   - 执行状态监控\n",
        "   - 结果智能聚合\n",
        "   - 异常处理和恢复\n",
        "\n",
        3. **上下文传递策略**：isolated vs fork\n",
        "   - isolated：隔离性好，避免污染\n",
        "   - fork：保持连续性，共享历史\n",
        "   - 自适应策略：基于任务特征自动选择\n",
        "\n",
        "## 技术亮点\n",
        "\n",
        "- 🤖 **多Agent系统**：支持复杂任务分解和并行执行\n",
        "- 🔄 **TaskFlow引擎**：完整的工作流生命周期管理\n",
        "- 🎯 **上下文管理**：智能的上下文策略选择和合并\n",
        "\n",
        "## 💡 业务关联思考\n",
        "\n",
        ### LangChat多Agent能力\n",
        "- **Subagent协作**：主Agent调用子Agent实现复杂业务流程\n",
        "- **Skill编排**：多个Skill协同完成综合任务\n",
        "- **上下文传递**：fork模式保持对话连续性\n",
        "\n",
        ### Orchestrator架构优势\n",
        "- **多Agent路由**：根据任务类型分配给最合适的Agent\n",
        "- **结果聚合**：智能整合多个Agent的执行结果\n",
        "- **监控追踪**：提供完整的执行链路信息\n",
        "\n",
        ### 商业地产应用场景\n",
        "- **商铺管理团队**：租赁+财务+客服+数据的Agent协作\n",
        "- **物业服务体系**：多Agent协同处理日常运营\n",
        "- **会员管理生态**：个性化服务、精准营销\n",
        "\n",
        ## 📈 学习进度更新\n",
        "\n",
        "✅ **W7 Day 4 完成** - 多Agent协作模式\n",
        "\n",
        "🎯 **明日预告**: W7 Day 5 - 评估体系\n",
        "\n",
        "- **性能评估**：响应速度、准确率、资源消耗\n",
        "- **质量评估**：任务完成度、用户体验、业务价值\n",
        "- **持续优化**：反馈循环、策略调整、能力升级"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🎯 学习进度追踪\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "from datetime import datetime\n",
        "\n",
        "def update_progress():\n",
        "    # 更新学习进度\n",
        "    progress_data = {\n",
        "        \"week\": 7,\n",
        "        \"day\": 4,\n",
        "        \"date\": datetime.now().strftime(\"%Y-%m-%d\"),\n",
        "        \"topic\": \"多Agent协作模式\",\n",
        "        \"status\": \"completed\",\n",
        "        \"key_concepts\": [\n",
        "            \"多Agent协作模式\",\n",
        "            \"TaskFlow工作流引擎\", \n",
        "            \"上下文传递策略\",\n",
        "            \"主Agent+子Agent架构\"\n",
        "        ]\n",
        "    }\n",
n",
        "    print(f\"🎯 进度更新: 第{progress_data['week']}周-第{progress_data['day']}天\")\n",
        "    print(f\"📚 主题: {progress_data['topic']}\")\n",
        "    print(f\"✅ 状态: {progress_data['status']}\")\n",
        "    print(\"🔑 核心概念:\")\n",
        "    for concept in progress_data['key_concepts']:\n",
        "        print(f\"  • {concept}\")\n",
n",
        "    return progress_data\n",
n",
        "# 更新进度\n",
        "current_progress = update_progress()\n",
n",
        "print(\"\\n\" + \"=\"*80)\n",
        "print(\"🎉 恭喜完成今日学习!\")\n",
        "print(\"💡 记住：多Agent协作让AI系统拥有了'团队协作'能力\")\n",
        "print(\"🚀 明天继续探索评估体系...\")"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.9.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}

# Generate notebook file
with open('/root/learning-notebooks/第7周/第7周-Day4-多Agent协作模式.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=2, ensure_ascii=False)

print("✅ Notebook文件已生成: /root/learning-notebooks/第7周/第7周-Day4-多Agent协作模式.ipynb")

# 验证JSON格式
try:
    with open('/root/learning-notebooks/第7周/第7周-Day4-多Agent协作模式.ipynb', 'r', encoding='utf-8') as f:
        json.load(f)
    print("✅ JSON格式验证通过")
except Exception as e:
    print(f"❌ JSON格式错误: {e}")

# Git操作
print("🔄 执行Git操作...")
import subprocess
subprocess.run(["git", "add", "."], cwd="/root/learning-notebooks/第7周")
subprocess.run(["git", "commit", "-m", "W7 Day4: 多Agent协作模式 - 主Agent+子Agent架构、TaskFlow工作流引擎、上下文传递策略"], cwd="/root/learning-notebooks/第7周")
subprocess.run(["git", "pull", "--rebase"], cwd="/root/learning-notebooks/第7周")
subprocess.run(["git", "push"], cwd="/root/learning-notebooks/第7周")

print("🎯 W7 Day4 学习流程完成！")