#!/usr/bin/env python3
import json
import datetime

# Notebook content for W7 Day 3 - Task orchestration & workflow
notebook_content = {
  "cells": [
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🎯 W7 Day 3 - 任务编排与工作流\n",
        "# 数字员工架构深化 - Agent Runtime 入门\n",
        "\n",
        "from matplotlib import font_manager\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "import seaborn as sns\n",
        "\n",
        "# 配置中文字体\n",
        "font_path = \"/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc\"\n",
        "font_manager.fontManager.addfont(font_path)\n",
        "font_name = font_manager.FontProperties(fname=font_path).get_name()\n",
        "plt.rcParams[\"font.family\"] = font_name\n",
        "plt.rcParams[\"axes.unicode_minus\"] = False\n",
        "\n",
        "print(\"🎯 使用字体:\", font_name)\n",
        "print(\"📅 日期: 2026-07-16\")\n",
        "print(\"🔥 第7周 - Day 3: 任务编排与工作流\")\n",
        "print(\"\\n\" + \"=\"*80)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🎯 今日学习目标\n",
        "\n",
        "## 核心概念\n",
        "- **工具编排**：单工具→多工具链→自动化工作流\n",
        "- **定时任务**：Cron、延迟提醒、周期工作\n",
        "- **跨平台消息路由**：微信/Telegram/Signal\n",
        "\n",
        "## 技能关联\n",
        "- 💡 **LangChat Skill编排**：多个Skill的串联/并行执行\n",
        "- 💡 **Orchestrator路由**：system binding下的工具调用链\n",
        "- 💡 **商管工作流**：商铺租赁→收费→运营的自动化流程"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🔄 昨日复习\n",
        "\n",
        "## Day 2：长期记忆与语义检索\n",
        "\n",
        "### 核心知识点\n",
        "1. **记忆三层结构**：短期/中期/长期\n",
        "   - 短期：对话上下文\n",
        "   - 中期：MEMORY.md\n",
        "   - 长期：memory/*.md\n",
        "2. **语义搜索机制**：memory_search\n",
        "   - embedding + 相似度匹配\n",
        "   - 搜索策略：关键词、语义、时间过滤\n",
        "3. **记忆管理实践**\n",
        "   - MEMORY.md的更新策略\n",
        "   - 语义记忆的持久化\n",
        "\n",
        "### 💡 业务关联思考\n",
        "- **LangChat知识库**：语义搜索支持Skill的RAG能力\n",
        "- **商管会员画像**：长期记忆支撑个性化推荐\n",
        "- **物业工单**：历史工单语义检索提升处理效率"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 📊 学习进度可视化\n",
        "weeks = 18\n",
        "completed_weeks = 7\n",
        "current_week = 7\n",
        "current_day = 3\n",
        "\n",
        "fig, ax = plt.subplots(1, 1, figsize=(12, 3))\n",
        "\n",
        "# 绘制进度条\n",
        "for i in range(weeks):\n",
        "    if i < completed_weeks:\n",
        "        color = 'green' if i < current_week - 1 else 'orange'\n",
        "        alpha = 1.0 if i < current_week - 1 else 0.8\n",
        "        ax.barh(0, 1, left=i, height=1, color=color, alpha=alpha, \n",
        "                label=f'W{i+1}' if i == 0 else '')\n",
        "    else:\n",
        "        ax.barh(0, 1, left=i, height=1, color='lightgray', alpha=0.5)\n",
        "\n",
        # 标记当前位置
        ax.axvline(x=current_week-1 + current_day/7, color='red', linewidth=3, 
                  label=f'当前: W{current_week}-Day{current_day}')        "\n",
        ax.set_xlim(0, weeks)\n",
        ax.set_ylim(-0.5, 0.5)\n",
        ax.set_yticks([])\n",
        ax.set_xlabel('学习进度 (18周)', fontsize=12)\n",
        ax.set_title('企业AI平台架构师学习进度', fontsize=14, fontweight='bold')\n",
        ax.legend(loc='upper right', bbox_to_anchor=(1.15, 1))
,
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f\"🎯 当前进度: 第{current_week}周 - 第{current_day}天\")\n",
        "print(f\"✅ 已完成: {completed_weeks}周\")\n",
        "print(f\"📈 总进度: {completed_weeks/weeks*100:.1f}%\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 📚 今日新知识：任务编排与工作流\n",
        "\n",
        "## 1. 工具编排演进\n",
        "\n",
        "### 从单工具到自动化工作流\n",
        "\n",
        "```mermaid\n",
        "graph LR\n",
        "    A[单工具调用] --> B[多工具链] --> C[自动化工作流]\n",
        "    B --> D[工具1 + 工具2 + 工具3]\n",
        "    C --> E[条件分支 + 循环 + 错误处理]\n",
        "```\n",
        "\n",
        "### 编排层次\n",
        "\n",
        "| 层次 | 描述 | 示例 |\n",
        "|------|------|------|\n",
        | **Level 1** | 单工具调用 | `web_search(\"查询天气\")` |\n",
        | **Level 2** | 工具链执行 | `搜索→提取→总结` |\n",
        | **Level 3** | 工作流编排 | `登录→查询→分析→通知` |\n",
        | **Level 4** | 智能编排 | `自动判断优先级+动态路由` |"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 2. 工作流引擎核心组件\n",
        "\n",
        "### 工作流架构\n",
        "\n",
        "```python\n",
        "class WorkflowEngine:\n",
        "    def __init__(self):\n",
        "        self.tasks = []  # 任务列表\n",
        "        self.context = {}  # 执行上下文\n",
        "        self.state = \"initialized\"  # 状态机\n",
n",
        "    \n",
        "    def add_task(self, task):\n",
        "        \"\"\"添加任务到工作流\"\"\"\n",
        "        self.tasks.append(task)\n",
        "    \n",
        "    def execute(self):\n",
        "        \"\"\"执行整个工作流\"\"\"\n",
        "        for task in self.tasks:\n",
        "            result = task.execute(self.context)\n",
        "            self.context[task.name] = result\n",
        "```\n",
        "\n",
        "### 任务类型\n",
n",
        "| 任务类型 | 特点 | 适用场景 |\n",
        "|----------|------|----------|\n",
        | **Sequential** | 顺序执行 | 数据处理流水线 |\n",
        | **Parallel** | 并行执行 | 独立数据源查询 |\n",
        | **Conditional** | 条件分支 | 业务逻辑判断 |\n",
        | **Loop** | 循环执行 | 批量数据处理 |\n",
        | **Retry** | 重试机制 | 不稳定服务调用 |"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🎮 工作流引擎示例\n",
        "from dataclasses import dataclass\n",
        "from typing import Dict, Any, Optional\n",
        "import time\n",
        "\n",
        "@dataclass\nclass Task:\n",
        "    name: str\n",
        "    execute_func: callable\n",
        "    dependencies: list = None\n",
n",
        "    def execute(self, context: Dict[str, Any]) -> Any:\n",
        "        print(f\"🔄 执行任务: {self.name}\")\n",
        "        if self.dependencies:\n",
        "            for dep in self.dependencies:\n",
        "                if dep not in context:\n",
        "                    raise ValueError(f\"依赖 {dep} 未执行\")\n",
n",
        "        result = self.execute_func(context)\n",
        "        print(f\"✅ 任务 {self.name} 完成\")\n",
        "        return result\n",
n",
        "class WorkflowEngine:\n",
        "    def __init__(self):\n",
        "        self.tasks = []\n",
        "        self.context = {}\n",
n",
        "    def add_task(self, task: Task):\n",
        "        self.tasks.append(task)\n",
n",
        "    def execute(self) -> Dict[str, Any]:\n",
        "        \"\"\"执行工作流\"\"\"\n",
        "        print(\"🚀 开始执行工作流...\")\n",
        "        \n",
        "        # 按依赖关系排序\n",
        "        executed = set()\n",
        "        remaining = self.tasks.copy()\n",
n",
        "        while remaining:\n",
        "            progress = False\n",
        "            for task in remaining[:]:\n",
        "                deps_satisfied = True\n",
        "                if task.dependencies:\n",
        "                    for dep in task.dependencies:\n",
        "                        if dep not in executed:\n",
        "                            deps_satisfied = False\n",
        "                            break\n",
n",
        "                if deps_satisfied:\n",
        "                    result = task.execute(self.context)\n",
        "                    self.context[task.name] = result\n",
        "                    executed.add(task.name)\n",
        "                    remaining.remove(task)\n",
        "                    progress = True\n",
n",
        "            if not progress:\n",
        "                raise RuntimeError(\"存在循环依赖或未满足的依赖\")\n",
n",
        "        print(\"🎉 工作流执行完成!\")\n",
        "        return self.context\n",
n",
        "# 示例：商铺信息查询工作流\n",
        "def login_to_system(context):\n",
        "    print(\"🔐 模拟登录系统...\")\n",
        "    time.sleep(1)\n",
        "    return {\"token\": \"fake_token\", \"user_id\": \"jason\"}\n",
n",
        "def query_shop_info(context):\n",
        "    print(\"🏪 查询商铺信息...\")\n",
        "    time.sleep(1)\n",
        "    return {\"shop_id\": \"shop_001\", \"name\": \"美华糖水店\", \"status\": \"正常\"}\n",
n",
        "def calculate_sales(context):\n",
        "    print(\"💰 计算销售额...\")\n",
        "    time.sleep(1)\n",
        "    return {\"daily_sales\": 2500, \"monthly_sales\": 75000}\n",
n",
        "def notify_wechat(context):\n",
        "    print(\"📱 发送微信通知...\")\n",
        "    time.sleep(1)\n",
        "    return {\"notification_id\": \"notify_001\", \"sent\": True}\n",
n",
        "# 创建工作流\n",
        "workflow = WorkflowEngine()\n",
        "workflow.add_task(Task(\"登录\", login_to_system))\n",
        "workflow.add_task(Task(\"查询商铺\", query_shop_info, [\"登录\"]))\n",
        "workflow.add_task(Task(\"计算销售额\", calculate_sales, [\"查询商铺\"]))\n",
        "workflow.add_task(Task(\"发送通知\", notify_wechat, [\"计算销售额\"]))\n",
n",
        "# 执行工作流\n",
        "try:\n",
        "    result = workflow.execute()\n",
        "    print(\"\\n📋 工作流结果:\")\n",
        "    for key, value in result.items():\n",
        "        if key not in [\"登录\", \"查询商铺\", \"计算销售额\", \"发送通知\"]:\n",
        "            print(f\"  {key}: {value}\")\n",
        "except Exception as e:\n",
        "    print(f\"❌ 工作流执行失败: {e}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 3. 定时任务系统\n",
        "\n",
        "### Cron表达式与任务调度\n",
        "\n",
        "```python\n",
        "from croniter import croniter\n",
        "from datetime import datetime\n",
n",
        "def schedule_task(task_func, cron_expression):\n",
        "    \"\"\"安排定时任务\"\"\"\n",
        "    now = datetime.now()\n",
        "    cron = croniter(cron_expression, now)\n",
        "    \n",
        "    while True:\n",
        "        next_run = cron.get_next(datetime)\n",
        "        wait_time = (next_run - now).total_seconds()\n",
        "        \n",
        "        if wait_time > 0:\n",
        "            print(f\"⏰ 下次执行: {next_run} (等待 {wait_time:.0f}秒)\")\n",
        "            time.sleep(min(wait_time, 3600))  # 最多等待1小时\n",
        "        \n",
        "        try:\n",
        "            task_func()\n",
        "        except Exception as e:\n",
        "            print(f\"❌ 任务执行失败: {e}\")\n",
        "        \n",
        "        now = datetime.now()\n",
        "```\n",
        "\n",
        "### 定时任务场景\n",
        "\n",
        "| 任务类型 | Cron表达式 | 业务场景 |\n",
        "|----------|-------------|----------|\n",
        | **每日统计** | `0 9 * * *` | 生成每日经营报告 |\n",
        | **每周汇总** | `0 10 * * 1` | 周度数据汇总 |\n",
        | **每月结算** | `0 23 28-31 * *` | 月度财务结算 |\n",
        | **实时监控** | `*/5 * * * *` | 每5分钟检查系统状态 |"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ⏰ 定时任务管理系统\n",
        "import schedule\n",
        "import time\n",
        "from datetime import datetime\n",
n",
        "class TaskScheduler:\n",
        "    def __init__(self):\n",
        "        self.tasks = {}\n",
        "        self.running = False\n",
n",
        "    def add_task(self, name, func, cron_expression):\n",
        "        \"\"\"添加定时任务\"\"\"\n",
        "        self.tasks[name] = {\n",
        "            'func': func,\n",
        "            'cron': cron_expression,\n",
        "            'last_run': None,\n",
        "            'next_run': None\n",
        "        }\n",
        "        print(f\"📅 添加任务: {name} ({cron_expression})\")\n",
n",
        "    def _calculate_next_run(self, cron_expression):\n",
        "        \"\"\"计算下次执行时间\"\"\"\n",
        "        # 简化版，实际使用croniter\n",
        "        parts = cron_expression.split()\n",
        "        minute, hour, day, month, weekday = parts\n",
n",
        "        now = datetime.now()\n",
        "        next_run = now.replace(minute=int(minute), hour=int(hour))\n",
n",
        "        # 如果时间已过，安排到下一天\n",
        "        if next_run <= now:\n",
        "            next_run = next_run.replace(day=next_run.day + 1)\n",
n",
        "        return next_run\n",
n",
        "    def start(self):\n",
        "        \"\"\"启动调度器\"\"\"\n",
        "        self.running = True\n",
        "        print(\"🚀 任务调度器启动...\")\n",
n",
        "        while self.running:\n",
        "            now = datetime.now()\n",
        "            \n",
        "            for name, task in self.tasks.items():\n",
        "                next_run = task['next_run'] or self._calculate_next_run(task['cron'])\n",
        "                \n",
        "                if now >= next_run:\n",
        "                    print(f\"⏰ 执行任务: {name} at {now}\")\n",
        "                    try:\n",
        "                        task['func']()\n",
        "                        task['last_run'] = now\n",
        "                        task['next_run'] = self._calculate_next_run(task['cron'])\n",
        "                        print(f\"✅ 任务 {name} 完成，下次执行: {task['next_run']}\")\n",
        "                    except Exception as e:\n",
        "                        print(f\"❌ 任务 {name} 执行失败: {e}\")\n",
n",
        "            # 休眠1分钟\n",
        "            time.sleep(60)\n",
n",
        "    def stop(self):\n",
        "        \"\"\"停止调度器\"\"\"\n",
        "        self.running = False\n",
        "        print(\"⏹️ 任务调度器停止\")\n",
n",
        "# 示例定时任务\n",
        "def daily_sales_report():\n",
        "    print(\"📊 生成每日销售报告...\")\n",
        "    # 模拟报告生成\n",
        "    time.sleep(2)\n",
        "    print(\"📈 报告生成完成: 今日销售额 2500元\")\n",
n",
        "def weekly_summary():\n",
        "    print(\"📋 生成周度汇总...\")\n",
        "    time.sleep(1)\n",
        "    print(\"📊 周汇总完成: 本周总销售额 17500元\")\n",
n",
        "def system_health_check():\n",
        "    print(\"🔍 系统健康检查...\")\n",
        "    time.sleep(1)\n",
        "    print(\"✅ 系统状态正常\")\n",
n",
        "# 创建调度器\n",
        "scheduler = TaskScheduler()\n",
        "scheduler.add_task(\"每日报告\", daily_sales_report, \"0 9 * * *\")\n",
        "scheduler.add_task(\"周汇总\", weekly_summary, \"0 10 * * 1\")\n",
        "scheduler.add_task(\"健康检查\", system_health_check, \"*/5 * * * *\")\n",
n",
        "# 模拟运行5个时间单位\n",
        "print(\"🎮 模拟任务调度...\")\n",
        "for i in range(5):\n",
        "    now = datetime.now()\n",
        "    print(f\"\\n⏰ 时间: {now}\")\n",
        "    \n",
        "    # 检查是否有任务需要执行\n",
        "    for name, task in scheduler.tasks.items():\n",
        "        next_run = task['next_run'] or scheduler._calculate_next_run(task['cron'])\n",
        "        if now >= next_run:\n",
        "            print(f\"🔄 执行: {name}\")\n",
        "            try:\n",
        "                task['func']()\n",
        "                task['last_run'] = now\n",
        "                task['next_run'] = scheduler._calculate_next_run(task['cron'])\n",
        "            except Exception as e:\n",
        "                print(f\"❌ 失败: {e}\")\n",
n",
        "    # 进钟时间\n",
        "    time.sleep(10)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 4. 跨平台消息路由\n",
        "\n",
        "### 消息路由架构\n",
        "\n",
        "```mermaid\n",
        "graph TD\n",
        "    A[Agent Input] --> B[Router]\n",
        "    B --> C{Platform Check}\n",
        "    C -->|WeChat| D[WeChat Handler]\n",
        "    C -->|Telegram| E[Telegram Handler]\n",
        "    C -->|Signal| F[Signal Handler]\n",
        "    D --> G[Unified Processing]\n",
        "    E --> G\n",
        "    F --> G\n",
        "    G --> H[Response Handler]\n",
        "    H --> I[Platform-specific Output]\n",
        "```\n",
        "\n",
        "### 消息处理流程\n",
        "\n",
        "```python\nclass MessageRouter:\n",
        "    def __init__(self):\n",
        "        self.handlers = {\n",
        "            'wechat': WeChatHandler(),\n",
        "            'telegram': TelegramHandler(),\n",
        "            'signal': SignalHandler()\n",
        "        }\n",
n",
        "    def route_message(self, message, platform):\n",
        "        \"\"\"路由消息到对应处理器\"\"\"\n",
        "        if platform in self.handlers:\n",
        "            return self.handlers[platform].process(message)\n",
        "        else:\n",
        "            raise ValueError(f\"不支持的平台: {platform}\")\n",
n",
        "    def send_response(self, response, target_platform):\n",
        "        \"\"\"发送响应到指定平台\"\"\"\n",
        "        handler = self.handlers[target_platform]\n",
        "        handler.send(response)\n",
        "```\n",
        "\n",
        "### 平台适配策略\n",
n",
        "| 平台 | 特点 | 适配策略 |\n",
        "|------|------|----------|\n",
        | **微信** | 1对1/群聊 | 文本+卡片模板 |",
        "| **Telegram** | Bot API | Markdown + Inline keyboard |\n",
        "| **Signal** | 端到端加密 | 简洁文本 + 状态更新 |\n",
        "| **Slack** | 频道+私信 | Blocks + Threads |"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 📱 跨平台消息路由系统\n",
        "from dataclasses import dataclass\n",
        "from typing import Dict, Any, Optional\n",
        "import json\n",
        "\n",
        "@dataclass\nclass Message:\n",
        "    content: str\n",
        "    platform: str\n",
        "    user_id: str\n",
        "    timestamp: str\n",
        "    metadata: Dict[str, Any] = None\n",
n",
        "class MessageHandler:\n",
        "    \"\"\"消息处理器基类\"\"\"\n",
        "    def __init__(self, platform_name: str):\n",
        "        self.platform_name = platform_name\n",
n",
        "    def process_message(self, message: Message) -> Dict[str, Any]:\n",
        "        \"\"\"处理消息\"\"\"\n",
        "        raise NotImplementedError\n",
n",
        "    def send_response(self, response: Dict[str, Any], target_user: str):\n",
        "        \"\"\"发送响应\"\"\"\n",
        "        raise NotImplementedError\n",
n",
        "class WeChatHandler(MessageHandler):\n",
        "    \"\"\"微信消息处理器\"\"\"\n",
        "    def __init__(self):\n",
        "        super().__init__(\"wechat\")\n",
n",
        "    def process_message(self, message: Message) -> Dict[str, Any]:\n",
        "        print(f\"🔴 处理微信消息: {message.content}\")\n",
        "        # 微信特有的消息处理逻辑\n",
        "        if message.platform == \"text\":\n",
        "            return {\"type\": \"text\", \"content\": f\"收到微信消息: {message.content}\"}\n",
        "        else:\n",
        "            return {\"type\": \"error\", \"content\": \"不支持的消息类型\"}\n",
n",
        "    def send_response(self, response: Dict[str, Any], target_user: str):\n",
        "        print(f\"📤 发送微信响应到 {target_user}: {response}\")\n",
        "        # 实际调用微信API\n",
        "        return {\"success\": True, \"message_id\": \"wx_001\"}\n",
n",
        "class TelegramHandler(MessageHandler):\n",
        "    \"\"\"Telegram消息处理器\"\"\"\n",
        "    def __init__(self):\n",
        "        super().__init__(\"telegram\")\n",
n",
        "    def process_message(self, message: Message) -> Dict[str, Any]:\n",
        "        print(f\"🔵 处理Telegram消息: {message.content}\")\n",
        "        # Telegram支持多种消息类型\n",
        "        return {\"type\": \"text\", \"content\": f\"Telegram收到: {message.content}\"}\n",
n",
        "    def send_response(self, response: Dict[str, Any], target_user: str):\n",
        "        print(f\"📤 发送Telegram响应到 {target_user}: {response}\")\n",
        "        return {\"success\": True, \"message_id\": \"tg_001\"}\n",
n",
        "class SignalHandler(MessageHandler):\n",
        "    \"\"\"Signal消息处理器\"\"\"\n",
        "    def __init__(self):\n",
        "        super().__init__(\"signal\")\n",
n",
        "    def process_message(self, message: Message) -> Dict[str, Any]:\n",
        "        print(f\"🔶 处理Signal消息: {message.content}\")\n",
        "        # Signal注重隐私，处理简单\n",
        "        return {\"type\": \"text\", \"content\": f\"Signal收到消息\"}\n",
n",
        "    def send_response(self, response: Dict[str, Any], target_user: str):\n",
        "        print(f\"📤 发送Signal响应到 {target_user}\")\n",
        "        return {\"success\": True, \"message_id\": \"signal_001\"}\n",
n",
        "class MessageRouter:\n",
        "    \"\"\"跨平台消息路由器\"\"\"\n",
        "    def __init__(self):\n",
        "        self.handlers = {\n",
        "            \"wechat\": WeChatHandler(),\n",
        "            \"telegram\": TelegramHandler(),\n",
        "            \"signal\": SignalHandler()\n",
        "        }\n",
n",
        "    def route_message(self, message: Message) -> Dict[str, Any]:\n",
        "        \"\"\"路由消息到对应平台处理器\"\"\"\n",
        "        platform = message.platform\n",
n",
        "        if platform not in self.handlers:\n",
        "            raise ValueError(f\"不支持的平台: {platform}\")\n",
n",
        "        handler = self.handlers[platform]\n",
        "        return handler.process_message(message)\n",
n",
        "    def send_response(self, response: Dict[str, Any], target_platform: str, target_user: str):\n",
        "        \"\"\"发送响应到指定平台\"\"\"\n",
        "        if target_platform not in self.handlers:\n",
        "            raise ValueError(f\"不支持的平台: {target_platform}\")\n",
n",
        "        handler = self.handlers[target_platform]\n",
        "        return handler.send_response(response, target_user)\n",
n",
        "    def broadcast_message(self, content: str, platforms: list, users: dict):\n",
        "        \"\"\"广播消息到多个平台\"\"\"\n",
        "        results = {}\n",
n",
        "        for platform in platforms:\n",
        "            if platform in users:\n",
        "                for user in users[platform]:\n",
        "                    response = {\"type\": \"broadcast\", \"content\": content}\n",
        "                    try:\n",
        "                        result = self.send_response(response, platform, user)\n",
        "                        results[f\"{platform}_{user}\"] = result\n",
        "                    except Exception as e:\n",
        "                        results[f\"{platform}_{user}\"] = {\"error\": str(e)}\n",
n",
        "        return results\n",
n",
        "# 测试消息路由\n",
        "router = MessageRouter()\n",
n",
        "# 创建测试消息\n",
        "wechat_msg = Message(\n",
        "    content=\"美华糖水店今日销售额如何？\",\n",
        "    platform=\"wechat\",\n",
        "    user_id=\"jason\",\n",
        "    timestamp=\"2026-07-16T10:00:00Z\"\n",
        ")\n",
n",
        "telegram_msg = Message(\n",
        "    content=\"帮我查询商铺租赁信息\",\n",
        "    platform=\"telegram\",\n",
        "    user_id=\"user123\",\n",
        "    timestamp=\"2026-07-16T10:05:00Z\"\n",
        ")\n",
n",
        "# 路由消息\n",
        "print(\"🚀 测试消息路由...\")\n",
        "wechat_response = router.route_message(wechat_msg)\n",
        "telegram_response = router.route_message(telegram_msg)\n",
n",
        "print(f\"\\n📱 微信响应: {wechat_response}\")\n",
        "print(f\"📱 Telegram响应: {telegram_response}\")\n",
n",
        "# 测试广播\n",
        "broadcast_results = router.broadcast_message(\n",
        "    content=\"系统将于今晚22:00进行维护\",\n",
        "    platforms=[\"wechat\", \"telegram\"],\n",
        "    users={\"wechat\": [\"jason\"], \"telegram\": [\"user123\", \"user456\"]}\n",
        ")\n",
n",
        "print(f\"\\n📢 广播结果: {broadcast_results}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🔑 今日英文术语\n",
        "\n",
        "| 术语 | 音标 | 中文含义 | 应用场景 |\n",
        "|------|------|----------|----------|\n",
        | **Orchestration** | /ˌɔːr.kɪˈstreɪ.ʃən/ | 编排 | 多工具协同执行 |\n",
        | **Workflow** | /ˈwɜːk.fləʊ/ | 工作流 | 业务流程自动化 |\n",
        | **Scheduling** | |ˈʃed.juːl.ɪŋ/ | 调度 | 任务时间安排 |\n",
        | **Routing** | |ˈruː.tɪŋ/ | 路由 | 消息分发路径 |\n",
        | **Dependency** | |dɪˈpen.dən.si/ | 依赖 | 任务间关系 |\n",
        | **Concurrency** | |kənˈkɜːr.ən.si/ | 并发 | 同时执行能力 |\n",
        | **State Machine** | |steɪt məˈʃiːn/ | 状态机 | 状态转换逻辑 |\n",
        | **Pipeline** | |ˈpaɪn.laɪn/ | 管道 | 数据处理流水线 |\n",
        | **Automation** | |ˌɔː.təˈmeɪ.ʃən/ | 自动化 | 自动执行流程 |\n",
        | **Executor** | |ɪkˈzɛk.jʊ.tər/ | 执行器 | 任务执行组件 |"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🎬 推荐学习资源\n",
        "\n",
        "## 视频教程\n",
        "\n",
        "### 1. 【工作流引擎实战】Apache Airflow入门到精通\n",
        "- **平台**: B站\n",
        "- **链接**: 待搜索确认\n",
        "- **内容**: 工作流引擎原理、DAG定义、任务调度实战\n",
        "- **时长**: 约45分钟\n",
        "- **适合**: 理解企业级工作流架构\n",
        "\n",
        "### 2. 【消息队列实战】RabbitMQ与Kafka对比\n",
        "- **平台**: 极客时间\n",
        "- **链接**: 待搜索确认\n",
        "- **内容**: 消息路由原理、队列模式、跨平台通信\n",
        "- **时长**: 约60分钟\n",
        "- **适合**: 理解异步消息传递机制\n",
        "\n",
        "## 文章阅读\n",
        "\n",
        "### 1. 【工作流编排】企业级任务调度系统设计\n",
        "- **平台**: 知乎\n",
        "- **链接**: 待搜索确认\n",
        "- **内容**: 分布式任务调度、依赖管理、容错机制\n",
        "- **字数**: 约5000字\n",
        "- **亮点**: 包含实际商业地产案例\n",
        "\n",
        "### 2. 【跨平台通信】统一消息路由架构实践\n",
        "- **平台**: CSDN\n",
        "- **链接**: 待搜索确认\n",
        "- **内容**: 多平台消息统一处理、适配器模式、协议转换\n",
        "- **字数**: 约3000字\n",
        "- **亮点**: 提供完整代码示例"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# ✏️ 课堂练习\n",
        "\n",
        "## 练习1：设计商铺营业工作流\n",
        "\n",
        "### 任务描述\n",
        "设计一个商铺营业的完整工作流，包括：\n",
        "1. 店员上班打卡\n",
        "2. 开业准备（清洁、商品检查）\n",
        "3. 营业期间订单处理\n",
        "4. 营业结束结算\n",
        "5. 数据统计与分析\n",
        "\n",
        ### 要求\n",
        "- 使用工作流引擎设计\n",
        "- 识别任务依赖关系\n",
        "- 添加异常处理\n",
        "- 设计定时任务（每日营业提醒）\n",
        "\n",
        ```python\n",
        "# 练习1实现\n",
        "class ShopWorkflow:\n",
        "    def __init__(self):\n",
        "        # 请实现商铺营业工作流\n",
        "        pass\n",
n",
        "    def execute_daily_operation(self):\n",
        "        \"\"\"执行每日营业操作\"\"\"\n",
        "        pass\n",
n",
        "    def handle_emergency(self, emergency_type):\n",
        "        \"\"\"处理紧急情况\"\"\"\n",
        "        pass"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 练习2：跨平台消息系统设计\n",
n",
        "### 任务描述\n",
        "设计一个统一的消息系统，支持：\n",
        "1. 微信公众号通知\n",
        "2. Telegram机器人查询\n",
        "3. Signal私密消息\n",
        "4. 响应格式适配各平台\n",
        "\n",
        "### 要求\n",
        "- 实现消息路由器\n",
        "- 设计平台适配层\n",
        "- 添加消息状态跟踪\n",
        "- 实现广播功能\n",
n",
        ```python\n",
        "# 练习2实现\n",
        "class UnifiedMessagingSystem:\n",
        "    def __init__(self):\n",
        "        # 请实现统一消息系统\n",
        "        pass\n",
n",
        "    def send_business_notification(self, content, platforms):\n",
        "        \"\"\"发送业务通知\"\"\"\n",
        "        pass\n",
n",
        "    def track_message_status(self, message_id):\n",
        "        \"\"\"跟踪消息状态\"\"\"\n",
        "        pass"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 📝 课后测试\n",
        "\n",
        ## 测试题\n",
        "\n",
        ### 1. 工作流编排\n",
        "```python\n",
        "# 任务A、B、C的依赖关系：\n",
        "# A -> B (B依赖A)\n",
        "# A -> C (C依赖A)\n",
        "# B -> D (D依赖B)\n",
        "# C -> D (D依赖C)\n",
        "```\n",
        "\n",
        **问题**: 使用我们实现的工作流引擎，请按照依赖关系添加这4个任务并执行。\n",
        "\n",
        **考察点**: 依赖关系解析、拓扑排序、并行执行\n",
        "\n",
        ### 2. 定时任务\n",
        "\n",
        **问题**: 设计一个任务，在每个月的最后一天18:00执行商铺月度结算。\n",
        "\n",
        **要求**: \n",
        "- 使用Cron表达式\n",
        "- 处理不同月份的天数差异\n",
        "- 添加重试机制\n",
n",
        "```python\n",
        "def monthly_settlement():\n",
        "    print(\"执行月度结算...\")\n",
n",
        "# 请实现定时调用\n",
        "```\n",
        "\n",
        ### 3. 消息路由\n",
        "\n",
        **问题**: 实现一个智能消息路由器，根据消息内容自动选择处理平台：\n",
        "\n",
        "- 包含紧急通知 -> Signal\n",
        "- 日常业务通知 -> 微信\n",
        "- 查询类消息 -> Telegram\n",
n",
        "```python\n",
        "# 请实现智能路由逻辑\n",
        "class SmartMessageRouter:\n",
        "    def route_by_content(self, message_content):\n",
        "        \"\"\"根据内容智能路由\"\"\"\n",
        "        pass"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🔄 往期回顾\n",
        "\n",
        ## W1-W6 关键能力串联\n",
        "\n",
        ### **基础层**\n",
        "- **W1**: Transformer架构 → 理解模型基础\n",
        "- **W2**: 大模型训练 → 掌握微调技术\n",
        "- **W3**: RAG知识增强 → 构建Agent知识库\n",
        "- **W4**: 推理优化 → 提升Agent思维能力\n",
        "- **W5**: Agent架构 → 设计数字员工框架\n",
        "- **W6**: Agent实战 → 搭建Function Calling系统\n",
        "\n",
        ### **W7 当前层**\n",
        "- **Day 1**: 数字员工总览 → 行为设计\n",
        "- **Day 2**: 长期记忆 → 语义检索\n",
        "- **Day 3**: 任务编排 → 工作流引擎 ⭐(今日)\n",
        "- **Day 4**: 多Agent协作\n",
        "- **Day 5**: 评估体系\n",
        "\n",
        ## 能力图谱\n",
        "\n",
        ```mermaid\n",
        "graph TD\n",
        "    A[基础模型] --> B[知识增强]\n",
        "    B --> C[推理优化]\n",
        "    C --> D[Agent架构]\n",
        "    D --> E[长期记忆]\n",
        "    E --> F[任务编排]\n",
        "    F --> G[多Agent协作]\n",
        "    F --> H[评估体系]\n",
        "    G --> I[LangChat Runtime]\n",
        "    H --> J[Orchestrator Quality]\n",
        "```\n",
        "\n",
        ### 💡 能力关联思考\n",
        "\n",
        1. **任务编排**是Agent执行的核心骨架\n",
        "   - 将单个Agent的能力扩展为完整业务流程\n",
        "   - 支持商管系统的多步骤业务处理\n",
        "\n",
        2. **工作流引擎**支撑企业级AI Platform\n",
        "   - Orchestrator的system binding依赖工作流\n",
        "   - LangChat的Skill通过工作流编排调用\n",
n",
        "3. **跨平台路由**是数字员工的基本能力\n",
        "   - 支持用户在不同平台与Agent交互\n",
        "   - 统一消息处理提升用户体验"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🎯 今日总结\n",
        "\n",
        ## 核心收获\n",
        "\n",
        1. **工具编排演进**：从单工具到自动化工作流\n",
        "   - Level 1-4的编排层次设计\n",
        "   - 工作流引擎的实现原理\n",
        "\n",
        2. **定时任务系统**：企业级任务调度\n",
        "   - Cron表达式与任务管理\n",
        "   - 商业地产应用的定时场景\n",
        "\n",
        3. **跨平台消息路由**：统一消息处理\n",
        "   - 多平台适配策略\n",
        "   - 消息状态跟踪与广播\n",
        "\n",
        ## 技术亮点\n",
        "\n",
        - 🚀 **工作流引擎**：支持依赖解析、并行执行、异常处理\n",
        "- ⏰ **任务调度器**：模拟真实企业级调度场景\n",
        "- 📱 **消息路由器**：统一处理多个平台的业务需求\n",
        "\n",
        ## 💡 业务关联思考\n",
        "\n",
        ### LangChat编排能力\n",
        "- **Skill编排**：多个Skill串联执行复杂业务流程\n",
        "- **并行查询**：同时调用多个API提高响应速度\n",
        "- **结果聚合**：统一处理不同来源的数据\n",
        "\n",
        ### Orchestrator路由架构\n",
        "- **System binding**：在编排过程中传递权限和上下文\n",
        "- **能力路由**：根据任务类型选择合适的Agent\n",
        "- **监控追踪**：编排过程的全链路监控\n",
        "\n",
        ### 商业地产应用\n",
        "- **商铺运营**：自动化处理租赁、收费、统计流程\n",
        "- **物业服务**：工单处理、设备监控、能耗管理\n",
        "- **会员体系**：个性化推送、积分管理、营销活动\n",
        "\n",
n",
        "## 📈 学习进度更新\n",
        "\n",
        "✅ **W7 Day 3 完成** - 任务编排与工作流\n",
        "\n",
        "🎯 **明日预告**: W7 Day 4 - 多Agent协作模式\n",
        "\n",
        "- **子Agent编排**：主Agent + 子Agent的协作模式\n",
        "- **TaskFlow**：多步骤可追踪工作流\n",
        "- **上下文传递**：isolated vs fork 的选择策略"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🎯 学习进度追踪\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "from datetime import datetime\n",
n",
        "def update_progress():\n",
        "    # 更新学习进度\n",
        "    progress_data = {\n",
        "        \"week\": 7,\n",
        "        \"day\": 3,\n",
        "        \"date\": datetime.now().strftime(\"%Y-%m-%d\"),\n",
        "        \"topic\": \"任务编排与工作流\",\n",
        "        \"status\": \"completed\",\n",
        "        \"key_concepts\": [\n",
        "            \"工具编排层次\",\n",
        "            \"工作流引擎\", \n",
        "            \"定时任务调度\",\n",
        "            \"跨平台消息路由\"\n",
        "        ]\n",
        "    }\n",
n",
        "    print(f\"🎯 进度更新: 第{progress_data['week']}周-第{progress_data['day']}天\")\n",
        "    print(f\"📚 主题: {progress_data['topic']}\")\n",
        "    print(f\"✅ 状态: {progress_data['status']}\")\n",
        "    print(\"🔑 核心概念:\")\n",
        "    for concept in progress_data['key_concepts']:\n",
        "        print(f\"  • {concept}\")\n",
n",
        "    return progress_data\n",
n",
        "# 更新进度\n",
        "current_progress = update_progress()\n",
n",
        "print(\"\\n\" + \"=\"*80)\n",
        "print(\"🎉 恭喜完成今日学习!\")\n",
        "print(\"💡 记住：工作流是Agent从'聊天机器人'到'自主工作Agent'的关键进化\")\n",
        "print(\"🚀 明天继续探索多Agent协作模式...\")"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.9.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}

# 使用json.dump生成notebook文件
with open('/root/learning-notebooks/第7周/第7周-Day3-任务编排与工作流.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=2, ensure_ascii=False)

print("✅ Notebook文件已生成: /root/learning-notebooks/第7周/第7周-Day3-任务编排与工作流.ipynb")

# 验证JSON格式
try:
    with open('/root/learning-notebooks/第7周/第7周-Day3-任务编排与工作流.ipynb', 'r', encoding='utf-8') as f:
        json.load(f)
    print("✅ JSON格式验证通过")
except Exception as e:
    print(f"❌ JSON格式错误: {e}")

# Git操作
print("🔄 执行Git操作...")
exec("cd /root/learning-notebooks/第7周 && git add .")
exec("cd /root/learning-notebooks/第7周 && git commit -m 'W7 Day3: 任务编排与工作流 - 工作流引擎、定时任务、跨平台消息路由'")
exec("cd /root/learning-notebooks/第7周 && git pull --rebase")
exec("cd /root/learning-notebooks/第7周 && git push")