import json

cells = []

# Cell 1: matplotlib font config (code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# W7 Day 6 - ⚡实战：搭建完整数字员工原型\n",
        "# matplotlib 中文字体配置\n",
        "from matplotlib import font_manager\n",
        "import matplotlib.pyplot as plt\n",
        "font_path = \"/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc\"\n",
        "font_manager.fontManager.addfont(font_path)\n",
        "font_name = font_manager.FontProperties(fname=font_path).get_name()\n",
        "plt.rcParams[\"font.family\"] = font_name\n",
        "plt.rcParams[\"axes.unicode_minus\"] = False\n",
        "print(f'中文字体配置完成: {font_name}')"
    ]
})

# Cell 2: Title and progress
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# ⚡ 实战日 | 第7周-Day6：搭建完整数字员工原型\n",
        "\n",
        "> **Agent Runtime入门 → 从零搭建一个可运行的数字员工**\n",
        "> 前五天我们学了：身份(SOUL.md) → 记忆(MEMORY.md) → 工作流 → 多Agent协作 → 质量评估\n",
        "> 今天是把所有知识串起来，动手搭建一个完整的数字员工原型！\n",
        "\n",
        "## 📅 学习进度\n",
        "\n",
        "```\n",
        "W1  ████████████████████ ✅ Transformer与大模型训练\n",
        "W2  ████████████████████ ✅ 微调与RLHF\n",
        "W3  ████████████████████ ✅ RAG与知识增强\n",
        "W4  ████████████████████ ✅ 推理与思维链\n",
        "W5  ████████████████████ ✅ Agent与工具使用\n",
        "W6  ████████████████████ ✅ LLM Agent实战\n",
        "W7  █████████████████░░░ 🔥 数字员工架构深化 (Day6/7)\n",
        "W8  ░░░░░░░░░░░░░░░░░░░░ 📝 AI基础补强\n",
        "W9  ░░░░░░░░░░░░░░░░░░░░ 🔌 MCP协议深入\n",
        "W10 ░░░░░░░░░░░░░░░░░░░░ ⚙️ Agent Runtime进阶\n",
        "W11 ░░░░░░░░░░░░░░░░░░░░ 🧠 AI Compiler\n",
        "W12 ░░░░░░░░░░░░░░░░░░░░ 🏛 Capability Platform\n",
        "W13 ░░░░░░░░░░░░░░░░░░░░ 📊 ChatBI\n",
        "W14 ░░░░░░░░░░░░░░░░░░░░ 🔒 企业权限与安全\n",
        "W15 ░░░░░░░░░░░░░░░░░░░░ 🎯 RL与优化\n",
        "W16 ░░░░░░░░░░░░░░░░░░░░ 👁 商业地产视觉AI\n",
        "W17 ░░░░░░░░░░░░░░░░░░░░ 🚀 前沿与部署\n",
        "W18 ░░░░░░░░░░░░░░░░░░░░ 🧠 脑科学精华\n",
        "```\n",
        "\n",
        "**进度: 7/18 周 (38.9%) | Day 34/126**"
    ]
})

# Cell 3: 往期回顾
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 🔄 往期回顾（W7 Day1-5 知识串联）\n",
        "\n",
        "## 本周学过的五大模块\n",
        "\n",
        "| Day | 主题 | 核心组件 | 一句话总结 |\n",
        "|-----|------|----------|-----------|\n",
        "| Day1 | 数字员工总览 | **SOUL.md** | 定义Agent的身份、规则、约束、输出格式 |\n",
        "| Day2 | 记忆系统 | **MEMORY.md** | 三层记忆（短期/中期/长期），语义搜索持久化 |\n",
        "| Day3 | 任务编排 | **Cron + 消息路由** | 工作流是图不是链，定时任务+跨平台推送 |\n",
        "| Day4 | 多Agent协作 | **subagent + TaskFlow** | 主Agent分发任务，子Agent并行执行 |\n",
        "| Day5 | 质量保障 | **护栏 + 监控** | 三层护栏(Prompt+工具+流程)，审计轨迹 |\n",
        "\n",
        "## 🎯 今天的任务\n",
        "\n",
        "把上面5个模块整合成一个**可运行的数字员工原型**：\n",
        "\n",
        "```\n",
        "用户请求 → OrchestratorAgent（身份+路由）\n",
        "              ├── SOUL.md（人格定义）\n",
        "              ├── MEMORY.md（记忆持久化）\n",
        "              ├── Tool Registry（工具注册表）\n",
        "              │    ├── 查询商铺信息\n",
        "              │    ├── 查询租赁状态\n",
        "              │    └── 发送通知\n",
        "              └── SubAgent池\n",
        "                   ├── 数据分析Agent\n",
        "                   └── 报告生成Agent\n",
        "```"
    ]
})

# Cell 4: Step1 SOUL.md
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 🏗️ Step 1：定义数字员工的 SOUL.md\n",
        "\n",
        "> SOUL.md = 数字员工的灵魂文件，定义身份、行为边界和输出规范\n",
        "\n",
        "## SOUL.md 四层结构回顾\n",
        "\n",
        "```\n",
        "Layer 1: Identity（身份）    → 你是谁？负责什么？\n",
        "Layer 2: Rules（规则）       → 工作流程是什么？先做什么后做什么？\n",
        "Layer 3: Constraints（约束） → 不能做什么？安全红线是什么？\n",
        "Layer 4: Output（输出格式）  → 交付物长什么样？JSON/Markdown/模板？\n",
        "```\n",
        "\n",
        "### 💡 LangChat/Orchestrator关联\n",
        "- LangChat中每个Skill都有System Prompt约束行为\n",
        "- Orchestrator通过SOUL.md判断请求路由到哪个能力域\n",
        "- 商管系统的数字员工需要严格遵守权限边界"
    ]
})

# Cell 5: SOUL.md code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Step 1: 定义商管数字员工的 SOUL.md\n",
        "SOUL_MD = \"\"\"# 商管数字员工 SOUL.md\n",
        "\n",
        "## Identity（身份）\n",
        "你是「商管智能助手」，服务于商业地产运营团队。\n",
        "你的职责包括：商铺信息查询、租赁状态跟踪、经营数据分析、异常预警。\n",
        "\n",
        "## Rules（工作规则）\n",
        "1. 收到查询请求时，先验证用户权限（是否属于运营组）\n",
        "2. 数据查询优先使用结构化API，知识查询使用RAG\n",
        "3. 涉及合同/租金等敏感数据，必须输出完整审计日志\n",
        "4. 无法确定时，转人工而不是猜测\n",
        "\n",
        "## Constraints（约束）\n",
        "- 禁止直接修改任何业务数据（只读 + 建议输出）\n",
        "- 禁止泄露租户联系方式给非授权人员\n",
        "- 超过权限范围的请求必须拒绝并上报\n",
        "\n",
        "## Output Format（输出格式）\n",
        "- 数据查询结果：结构化表格 + 摘要文字\n",
        "- 分析报告：Markdown格式，含数据来源标注\n",
        "- 预警通知：⚠️标识 + 紧急程度(低/中/高) + 建议操作\n",
        "\"\"\"\n",
        "\n",
        "print(SOUL_MD)\n",
        "print(f\"\\n📊 SOUL.md 总字数: {len(SOUL_MD)}\")"
    ]
})

# Cell 6: MEMORY.md
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 🧠 Step 2：设计 MEMORY.md 记忆系统\n",
        "\n",
        "> 数字员工需要记住用户偏好、历史决策、业务上下文\n",
        "\n",
        "## 三层记忆架构\n",
        "\n",
        "| 层次 | 存储位置 | 容量 | 持久性 | 用途 |\n",
        "|------|----------|------|--------|------|\n",
        "| 短期 | 上下文窗口 | ~4K tokens | 单次对话 | 当前对话的临时信息 |\n",
        "| 中期 | session历史 | ~32K tokens | 会话级 | 本轮对话的重要事实 |\n",
        "| 长期 | MEMORY.md + memory/*.md | 无限 | 永久 | 用户偏好、历史决策 |\n",
        "\n",
        "### 语义搜索原理\n",
        "```\n",
        "用户问 \"上次那个餐饮招商的分析\"\n",
        "  → embedding(查询语句) → 向量\n",
        "  → 在memory/*.md的embedding索引中搜索\n",
        "  → 余弦相似度排序\n",
        "  → 返回最相关的记忆片段\n",
        "```"
    ]
})

# Cell 7: MEMORY.md code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Step 2: 设计记忆系统\n",
        "MEMORY_MD = \"\"\"# MEMORY.md - 商管数字员工记忆\n",
        "\n",
        "## 用户偏好\n",
        "- Jason（运营总监）：偏好数据驱动决策，喜欢图表而非纯文字\n",
        "- Sarah（招商经理）：关注租赁转化率，偏好简洁摘要\n",
        "\n",
        "## 重要决策记录\n",
        "- 2026-06-15: 确认优先推广3F餐饮区域，目标品牌：海底捞、西贝\n",
        "- 2026-06-28: B1层儿童区改造方案获批，预计Q3完成\n",
        "\n",
        "## 业务上下文\n",
        "- 当前项目：万达广场浦东店\n",
        "- 总商铺数：285个，已出租：241个，空置率：15.4%\n",
        "- 重点KPI：客流增长率、坪效、租金收缴率\n",
        "\"\"\"\n",
        "\n",
        "# 模拟语义搜索\n",
        "import hashlib\n",
        "\n",
        "def simple_embedding(text, dim=64):\n",
        "    \"\"\"简易hash-based embedding（教学用，真实场景用Transformer）\"\"\"\n",
        "    words = text.replace('\\n', ' ').split()\n",
        "    vec = [0.0] * dim\n",
        "    for w in words:\n",
        "        h = int(hashlib.md5(w.encode()).hexdigest(), 16)\n",
        "        idx = h % dim\n",
        "        vec[idx] += 1.0\n",
        "    # 归一化\n",
        "    norm = sum(v*v for v in vec) ** 0.5\n",
        "    if norm > 0:\n",
        "        vec = [v/norm for v in vec]\n",
        "    return vec\n",
        "\n",
        "def cosine_sim(a, b):\n",
        "    return sum(x*y for x, y in zip(a, b))\n",
        "\n",
        "# 记忆片段库\n",
        "memory_chunks = [\n",
        "    \"Jason偏好数据驱动决策，喜欢图表\",\n",
        "    \"确认优先推广3F餐饮区域，目标品牌海底捞西贝\",\n",
        "    \"B1层儿童区改造方案获批\",\n",
        "    \"万达广场浦东店总商铺285个已出租241个\",\n",
        "    \"重点KPI客流增长率坪效租金收缴率\",\n",
        "]\n",
        "\n",
        "# 索引所有记忆\n",
        "embeddings = {chunk: simple_embedding(chunk) for chunk in memory_chunks}\n",
        "\n",
        "# 模拟查询\n",
        "query = \"餐饮招商分析\"\n",
        "query_vec = simple_embedding(query)\n",
        "\n",
        "scores = [(chunk, cosine_sim(query_vec, vec)) for chunk, vec in embeddings.items()]\n",
        "scores.sort(key=lambda x: -x[1])\n",
        "\n",
        "print(f'🔍 查询: \"{query}\"')\n",
        "print(f'\\n📊 语义搜索结果（按相似度排序）:')\n",
        "for i, (chunk, score) in enumerate(scores[:3], 1):\n",
        "    print(f'  {i}. [{score:.4f}] {chunk}')"
    ]
})

# Cell 8: Tool Registry
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 🔧 Step 3：工具注册表（Tool Registry）\n",
        "\n",
        "> 数字员工通过工具与外部系统交互。工具注册表管理所有可用工具的元数据。\n",
        "\n",
        "## 工具Schema设计\n",
        "\n",
        "每个工具需要：\n",
        "- **name**: 唯一标识\n",
        "- **description**: 功能描述（给LLM看的）\n",
        "- **parameters**: 输入参数Schema\n",
        "- **returns**: 输出格式\n",
        "- **permissions**: 调用权限要求\n",
        "\n",
        "### 💡 对应MCP协议\n",
        "- MCP Tool 就是结构化的工具定义\n",
        "- LangChat的Skill最终通过MCP暴露为标准能力\n",
        "- Orchestrator的capability路由基于工具注册表"
    ]
})

# Cell 9: Tool Registry code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Step 3: 定义工具注册表\n",
        "import json\n",
        "\n",
        "TOOL_REGISTRY = {\n",
        "    \"query_shop\": {\n",
        "        \"description\": \"查询商铺信息（铺位号、面积、业态、租户）\",\n",
        "        \"parameters\": {\n",
        "            \"type\": \"object\",\n",
        "            \"properties\": {\n",
        "                \"shop_id\": {\"type\": \"string\", \"description\": \"商铺编号，如B1-001\"},\n",
        "                \"floor\": {\"type\": \"string\", \"description\": \"楼层筛选，如3F\"}\n",
        "            }\n",
        "        },\n",
        "        \"required\": [\"shop_id\"],\n",
        "        \"permissions\": [\"read:shop\"],\n",
        "        \"timeout_ms\": 3000\n",
        "    },\n",
        "    \"query_lease\": {\n",
        "        \"description\": \"查询租赁状态（合同、租金、到期日）\",\n",
        "        \"parameters\": {\n",
        "            \"type\": \"object\",\n",
        "            \"properties\": {\n",
        "                \"shop_id\": {\"type\": \"string\"},\n",
        "                \"status\": {\"type\": \"string\", \"enum\": [\"active\", \"expired\", \"pending\"]}\n",
        "            }\n",
        "        },\n",
        "        \"required\": [\"shop_id\"],\n",
        "        \"permissions\": [\"read:lease\"],\n",
        "        \"timeout_ms\": 5000\n",
        "    },\n",
        "    \"send_notification\": {\n",
        "        \"description\": \"发送通知消息（邮件/短信/微信）\",\n",
        "        \"parameters\": {\n",
        "            \"type\": \"object\",\n",
        "            \"properties\": {\n",
        "                \"channel\": {\"type\": \"string\", \"enum\": [\"email\", \"sms\", \"wechat\"]},\n",
        "                \"recipient\": {\"type\": \"string\"},\n",
        "                \"message\": {\"type\": \"string\"},\n",
        "                \"priority\": {\"type\": \"string\", \"enum\": [\"low\", \"medium\", \"high\"]}\n",
        "            }\n",
        "        },\n",
        "        \"required\": [\"channel\", \"recipient\", \"message\"],\n",
        "        \"permissions\": [\"write:notification\"],\n",
        "        \"timeout_ms\": 2000\n",
        "    }\n",
        "}\n",
        "\n",
        "# 模拟工具执行\n",
        "MOCK_SHOP_DATA = {\n",
        "    \"3F-012\": {\"shop_id\": \"3F-012\", \"area\": 280, \"business\": \"餐饮\", \"tenant\": \"海底捞\", \"rent\": 85000},\n",
        "    \"3F-015\": {\"shop_id\": \"3F-015\", \"area\": 150, \"business\": \"餐饮\", \"tenant\": \"空置\", \"rent\": 0},\n",
        "    \"B1-008\": {\"shop_id\": \"B1-008\", \"area\": 45, \"business\": \"零售\", \"tenant\": \"名创优品\", \"rent\": 12000},\n",
        "}\n",
        "\n",
        "def execute_tool(tool_name, params):\n",
        "    \"\"\"模拟工具执行\"\"\"\n",
        "    if tool_name == \"query_shop\":\n",
        "        shop_id = params.get(\"shop_id\")\n",
        "        if shop_id in MOCK_SHOP_DATA:\n",
        "            return {\"status\": \"success\", \"data\": MOCK_SHOP_DATA[shop_id]}\n",
        "        return {\"status\": \"not_found\", \"data\": None}\n",
        "    elif tool_name == \"query_lease\":\n",
        "        shop_id = params.get(\"shop_id\")\n",
        "        if shop_id == \"3F-012\":\n",
        "            return {\"status\": \"success\", \"data\": {\"contract\": \"L2024-0231\", \"monthly_rent\": 85000, \"expire\": \"2027-03-31\"}}\n",
        "        return {\"status\": \"not_found\", \"data\": None}\n",
        "    elif tool_name == \"send_notification\":\n",
        "        return {\"status\": \"success\", \"message_id\": f\"MSG-{hash(params.get('message',''))%10000:04d}\"}\n",
        "    return {\"status\": \"error\", \"message\": f\"Unknown tool: {tool_name}\"}\n",
        "\n",
        "# 测试工具调用\n",
        "print('🔧 工具注册表:')\n",
        "for name, spec in TOOL_REGISTRY.items():\n",
        "    print(f'  - {name}: {spec[\"description\"]}')\n",
        "\n",
        "print('\\n🧪 测试工具调用:')\n",
        "result = execute_tool(\"query_shop\", {\"shop_id\": \"3F-012\"})\n",
        "print(f'  query_shop(3F-012) → {json.dumps(result, ensure_ascii=False, indent=2)}')"
    ]
})

# Cell 10: SubAgent
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 🤖 Step 4：子Agent协作设计\n",
        "\n",
        "> 主Agent（Orchestrator）负责路由，子Agent负责专业任务\n",
        "\n",
        "## 子Agent类型\n",
        "\n",
        "```\n",
        "OrchestratorAgent（主控）\n",
        "  ├── DataAgent（数据分析子Agent）\n",
        "  │    └── 负责SQL查询、数据汇总、趋势分析\n",
        "  ├── ReportAgent（报告生成子Agent）\n",
        "  │    └── 负责将分析结果转为可读报告\n",
        "  └── AlertAgent（预警子Agent）\n",
        "       └── 负责异常检测和通知推送\n",
        "```\n",
        "\n",
        "## 上下文传递：isolated vs fork\n",
        "\n",
        "| 模式 | 说明 | 适用场景 |\n",
        "|------|------|----------|\n",
        "| **isolated** | 子Agent获得干净上下文 | 独立任务（数据分析） |\n",
        "| **fork** | 子Agent继承父Agent对话历史 | 需要上下文的连续任务 |\n",
        "\n",
        "### 💡 OpenClaw的sessions_spawn\n",
        "```python\n",
        "# isolated模式（默认）\n",
        "sessions_spawn(task=\"分析3F餐饮区域经营数据\", context=\"isolated\")\n",
        "\n",
        "# fork模式（需要父对话上下文）\n",
        "sessions_spawn(task=\"继续刚才的分析，深入租金差异\", context=\"fork\")\n",
        "```"
    ]
})

# Cell 11: SubAgent code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Step 4: 子Agent模拟实现\n",
        "import time\n",
        "\n",
        "class SubAgent:\n",
        "    \"\"\"子Agent基类\"\"\"\n",
        "    def __init__(self, name, soul, tools, context_mode=\"isolated\"):\n",
        "        self.name = name\n",
        "        self.soul = soul  # 子Agent的SOUL.md\n",
        "        self.tools = tools  # 可用工具列表\n",
        "        self.context_mode = context_mode\n",
        "        self.results = []\n",
        "\n",
        "    def run(self, task, parent_context=None):\n",
        "        \"\"\"执行任务\"\"\"\n",
        "        print(f'  [{self.name}] 接收任务: {str(task)[:60]}')\n",
        "        if self.context_mode == \"fork\" and parent_context:\n",
        "            print(f'  [{self.name}] 继承父上下文 ({len(parent_context)} chars)')\n",
        "        else:\n",
        "            print(f'  [{self.name}] 使用隔离上下文 (isolated)')\n",
        "        # 模拟执行\n",
        "        time.sleep(0.1)\n",
        "        result = self._execute(task)\n",
        "        self.results.append(result)\n",
        "        return result\n",
        "\n",
        "    def _execute(self, task):\n",
        "        raise NotImplementedError\n",
        "\n",
        "\n",
        "class DataAgent(SubAgent):\n",
        "    \"\"\"数据分析子Agent\"\"\"\n",
        "    def __init__(self):\n",
        "        super().__init__(\n",
        "            name=\"DataAgent\",\n",
        "            soul=\"你是数据分析专家，负责SQL查询和数据汇总\",\n",
        "            tools=[\"query_shop\", \"query_lease\"],\n",
        "            context_mode=\"isolated\"\n",
        "        )\n",
        "\n",
        "    def _execute(self, task):\n",
        "        shops = []\n",
        "        for shop_id in [\"3F-012\", \"3F-015\"]:\n",
        "            result = execute_tool(\"query_shop\", {\"shop_id\": shop_id})\n",
        "            if result[\"status\"] == \"success\":\n",
        "                shops.append(result[\"data\"])\n",
        "        total_area = sum(s[\"area\"] for s in shops)\n",
        "        total_rent = sum(s[\"rent\"] for s in shops)\n",
        "        occupied = sum(1 for s in shops if s[\"tenant\"] != \"空置\")\n",
        "        return {\n",
        "            \"agent\": self.name,\n",
        "            \"analysis\": {\n",
        "                \"total_shops\": len(shops),\n",
        "                \"total_area\": total_area,\n",
        "                \"total_monthly_rent\": total_rent,\n",
        "                \"occupancy_rate\": f\"{occupied/len(shops)*100:.0f}%\",\n",
        "            }\n",
        "        }\n",
        "\n",
        "\n",
        "class ReportAgent(SubAgent):\n",
        "    \"\"\"报告生成子Agent\"\"\"\n",
        "    def __init__(self):\n",
        "        super().__init__(\n",
        "            name=\"ReportAgent\",\n",
        "            soul=\"你是报告撰写专家，将数据转为可读的商业分析报告\",\n",
        "            tools=[],\n",
        "            context_mode=\"fork\"\n",
        "        )\n",
        "\n",
        "    def _execute(self, task):\n",
        "        if isinstance(task, dict) and \"analysis\" in task:\n",
        "            a = task[\"analysis\"]\n",
        "            report = f\"\"\"📊 3F餐饮区域经营分析报告\n",
        "{'='*40}\n",
        "总商铺数: {a['total_shops']}\n",
        "总面积:   {a['total_area']}㎡\n",
        "月租金:   ¥{a['total_monthly_rent']:,}\n",
        "出租率:   {a['occupancy_rate']}\n",
        "{'='*40}\n",
        "💡 建议: 出租率偏低，建议加大招商力度。\"\"\"\n",
        "            return {\"agent\": self.name, \"report\": report}\n",
        "        return {\"agent\": self.name, \"report\": \"数据不足，无法生成报告\"}\n",
        "\n",
        "\n",
        "class AlertAgent(SubAgent):\n",
        "    \"\"\"预警子Agent\"\"\"\n",
        "    def __init__(self):\n",
        "        super().__init__(\n",
        "            name=\"AlertAgent\",\n",
        "            soul=\"你是预警监控专家，负责检测异常并推送通知\",\n",
        "            tools=[\"send_notification\"],\n",
        "            context_mode=\"isolated\"\n",
        "        )\n",
        "\n",
        "    def _execute(self, task):\n",
        "        if isinstance(task, dict) and \"analysis\" in task:\n",
        "            rate_str = task[\"analysis\"][\"occupancy_rate\"]\n",
        "            rate = int(rate_str.replace('%', ''))\n",
        "            if rate < 80:\n",
        "                result = execute_tool(\"send_notification\", {\n",
        "                    \"channel\": \"wechat\",\n",
        "                    \"recipient\": \"Jason\",\n",
        "                    \"message\": f\"⚠️ 3F餐饮区域出租率仅{rate_str}%，低于预警线80%\",\n",
        "                    \"priority\": \"high\"\n",
        "                })\n",
        "                return {\"agent\": self.name, \"alert_sent\": True, \"result\": result}\n",
        "        return {\"agent\": self.name, \"alert_sent\": False}\n",
        "\n",
        "\n",
        "print('🤖 子Agent注册完成:')\n",
        "for cls in [DataAgent, ReportAgent, AlertAgent]:\n",
        "    agent_tmp = cls()\n",
        "    print(f'  ✅ {agent_tmp.name} | tools={agent_tmp.tools} | context={agent_tmp.context_mode}')"
    ]
})

# Cell 12: OrchestratorAgent
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 🎯 Step 5：OrchestratorAgent — 把一切串起来\n",
        "\n",
        "> 主控Agent = SOUL.md + MEMORY.md + Tool Registry + SubAgent编排\n",
        "\n",
        "## 执行流程\n",
        "\n",
        "```\n",
        "1. 用户请求进来\n",
        "   \"分析一下3F餐饮区域的经营状况\"\n",
        "\n",
        "2. OrchestratorAgent 解析意图\n",
        "   → 意图: 数据分析 + 报告生成\n",
        "   → 路由: DataAgent → ReportAgent → AlertAgent\n",
        "\n",
        "3. 调用 DataAgent (isolated)\n",
        "   → 查询商铺数据 → 返回结构化分析结果\n",
        "\n",
        "4. 调用 ReportAgent (fork，继承DataAgent结果)\n",
        "   → 将数据转为可读报告\n",
        "\n",
        "5. 调用 AlertAgent (isolated)\n",
        "   → 检查是否需要预警 → 如出租率<80%，发送通知\n",
        "\n",
        "6. 整合所有结果，返回给用户\n",
        "```"
    ]
})

# Cell 13: OrchestratorAgent code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Step 5: OrchestratorAgent 完整实现\n",
        "\n",
        "class OrchestratorAgent:\n",
        "    \"\"\"数字员工主控Agent\"\"\"\n",
        "\n",
        "    def __init__(self, soul_md, memory_md, tool_registry):\n",
        "        self.soul = soul_md\n",
        "        self.memory = memory_md\n",
        "        self.tools = tool_registry\n",
        "        self.subagents = {}\n",
        "        self.audit_log = []\n",
        "        self.conversation_history = []\n",
        "\n",
        "    def register_subagent(self, name, agent):\n",
        "        self.subagents[name] = agent\n",
        "\n",
        "    def _log(self, action, details):\n",
        "        entry = {\n",
        "            \"timestamp\": time.strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
        "            \"action\": action,\n",
        "            \"details\": details\n",
        "        }\n",
        "        self.audit_log.append(entry)\n",
        "        print(f'  📝 [{entry[\"timestamp\"]}] {action}')\n",
        "\n",
        "    def _intent_classification(self, message):\n",
        "        \"\"\"简易意图识别\"\"\"\n",
        "        if \"分析\" in message or \"报告\" in message:\n",
        "            return \"data_analysis\"\n",
        "        elif \"查询\" in message or \"查\" in message:\n",
        "            return \"query\"\n",
        "        elif \"通知\" in message or \"提醒\" in message:\n",
        "            return \"notification\"\n",
        "        return \"unknown\"\n",
        "\n",
        "    def handle_request(self, user_message, user_id=\"Jason\"):\n",
        "        \"\"\"处理用户请求\"\"\"\n",
        "        print(f'\\n{\"=\"*60}')\n",
        "        print(f'👤 用户({user_id}): {user_message}')\n",
        "        print(f'{\"=\"*60}')\n",
        "\n",
        "        # 1. 记录到短期记忆\n",
        "        self.conversation_history.append({\"role\": \"user\", \"content\": user_message})\n",
        "        self._log(\"user_request\", {\"user\": user_id, \"message\": user_message})\n",
        "\n",
        "        # 2. 意图识别\n",
        "        intent = self._intent_classification(user_message)\n",
        "        print(f'\\n🧠 意图识别: {intent}')\n",
        "\n",
        "        # 3. 路由\n",
        "        if intent == \"data_analysis\":\n",
        "            return self._handle_analysis(user_message)\n",
        "        elif intent == \"query\":\n",
        "            return self._handle_query(user_message)\n",
        "        else:\n",
        "            response = \"抱歉，我目前支持数据分析和信息查询。请试试：'分析3F餐饮区域经营状况'\"\n",
        "            self.conversation_history.append({\"role\": \"assistant\", \"content\": response})\n",
        "            return response\n",
        "\n",
        "    def _handle_analysis(self, message):\n",
        "        \"\"\"处理分析类请求 - 多Agent协作\"\"\"\n",
        "        print(f'\\n🔄 启动多Agent协作流水线...')\n",
        "\n",
        "        # Step 1: DataAgent\n",
        "        print(f'\\n  Step 1: DataAgent 收集数据')\n",
        "        data_agent = self.subagents.get(\"data\")\n",
        "        data_result = data_agent.run(message)\n",
        "        self._log(\"subagent_complete\", {\"agent\": \"DataAgent\"})\n",
        "\n",
        "        # Step 2: ReportAgent (fork)\n",
        "        print(f'\\n  Step 2: ReportAgent 生成报告')\n",
        "        report_agent = self.subagents.get(\"report\")\n",
        "        report_result = report_agent.run(data_result, parent_context=str(data_result))\n",
        "        self._log(\"subagent_complete\", {\"agent\": \"ReportAgent\"})\n",
        "\n",
        "        # Step 3: AlertAgent\n",
        "        print(f'\\n  Step 3: AlertAgent 检查预警')\n",
        "        alert_agent = self.subagents.get(\"alert\")\n",
        "        alert_result = alert_agent.run(data_result)\n",
        "        self._log(\"subagent_complete\", {\"agent\": \"AlertAgent\"})\n",
        "\n",
        "        # 整合结果\n",
        "        final_response = report_result.get(\"report\", \"无报告\")\n",
        "        if alert_result.get(\"alert_sent\"):\n",
        "            final_response += f\"\\n\\n⚠️ 已通过微信推送预警通知给Jason\"\n",
        "\n",
        "        self.conversation_history.append({\"role\": \"assistant\", \"content\": final_response})\n",
        "        return final_response\n",
        "\n",
        "    def _handle_query(self, message):\n",
        "        \"\"\"处理查询类请求\"\"\"\n",
        "        for shop_id in [\"3F-012\", \"3F-015\", \"B1-008\"]:\n",
        "            if shop_id in message:\n",
        "                result = execute_tool(\"query_shop\", {\"shop_id\": shop_id})\n",
        "                self._log(\"tool_call\", {\"tool\": \"query_shop\", \"shop_id\": shop_id})\n",
        "                if result[\"status\"] == \"success\":\n",
        "                    d = result[\"data\"]\n",
        "                    response = f\"🏪 商铺 {shop_id}\\n面积: {d['area']}㎡\\n业态: {d['business']}\\n租户: {d['tenant']}\\n月租金: ¥{d['rent']:,}\"\n",
        "                    self.conversation_history.append({\"role\": \"assistant\", \"content\": response})\n",
        "                    return response\n",
        "        response = \"请提供具体的商铺编号，如3F-012\"\n",
        "        self.conversation_history.append({\"role\": \"assistant\", \"content\": response})\n",
        "        return response\n",
        "\n",
        "    def get_audit_log(self):\n",
        "        return self.audit_log\n",
        "\n",
        "\n",
        "# ========== 完整搭建数字员工 ==========\n",
        "print('🚀 正在搭建商管数字员工...\\n')\n",
        "\n",
        "agent = OrchestratorAgent(\n",
        "    soul_md=SOUL_MD,\n",
        "    memory_md=MEMORY_MD,\n",
        "    tool_registry=TOOL_REGISTRY\n",
        ")\n",
        "agent.register_subagent(\"data\", DataAgent())\n",
        "agent.register_subagent(\"report\", ReportAgent())\n",
        "agent.register_subagent(\"alert\", AlertAgent())\n",
        "\n",
        "print('✅ 商管数字员工搭建完成!')\n",
        "print(f'   - SOUL.md: {len(SOUL_MD)} 字符')\n",
        "print(f'   - MEMORY.md: {len(MEMORY_MD)} 字符')\n",
        "print(f'   - Tools: {list(TOOL_REGISTRY.keys())}')\n",
        "print(f'   - SubAgents: {list(agent.subagents.keys())}')"
    ]
})

# Cell 14: Run Demo
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 🎬 实战演示：数字员工处理真实请求\n",
        "\n",
        "# Demo 1: 分析请求\n",
        "response1 = agent.handle_request(\"帮我分析3F餐饮区域的经营状况\")\n",
        "print(f'\\n🤖 数字员工回答:\\n{response1}')\n",
        "\n",
        "print('\\n' + '─'*60 + '\\n')\n",
        "\n",
        "# Demo 2: 查询请求\n",
        "response2 = agent.handle_request(\"查询商铺3F-012的信息\")\n",
        "print(f'\\n🤖 数字员工回答:\\n{response2}')"
    ]
})

# Cell 15: Audit Log
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 📋 查看审计日志\n",
        "print('📋 审计日志（Audit Trail）')\n",
        "print('='*60)\n",
        "for i, log in enumerate(agent.get_audit_log(), 1):\n",
        "    print(f'{i}. [{log[\"timestamp\"]}] {log[\"action\"]}')\n",
        "    print(f'   详情: {json.dumps(log[\"details\"], ensure_ascii=False)[:100]}')\n",
        "    print()\n",
        "print(f'总日志条数: {len(agent.get_audit_log())}')\n",
        "print('💡 对应Day5学到的审计轨迹：谁、什么时候、做了什么、结果如何')"
    ]
})

# Cell 16: Visualization
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 📊 可视化：数字员工架构图\n",
        "fig, ax = plt.subplots(1, 1, figsize=(14, 8))\n",
        "ax.set_xlim(0, 14)\n",
        "ax.set_ylim(0, 10)\n",
        "ax.set_aspect('equal')\n",
        "ax.axis('off')\n",
        "ax.set_title('商管数字员工架构图', fontsize=18, fontweight='bold', pad=20)\n",
        "\n",
        "c_user = '#4ECDC4'\n",
        "c_orch = '#FF6B6B'\n",
        "c_soul = '#95E1D3'\n",
        "c_sub = '#FDA085'\n",
        "c_tool = '#A8DADC'\n",
        "\n",
        "# 用户\n",
        "ax.add_patch(plt.Circle((2, 5), 0.8, color=c_user, ec='black', lw=2))\n",
        "ax.text(2, 5, '👤\\n用户', ha='center', va='center', fontsize=11, fontweight='bold')\n",
        "\n",
        "# OrchestratorAgent\n",
        "ax.add_patch(plt.Rectangle((5.5, 3.5), 3, 3, color=c_orch, alpha=0.8, ec='black', lw=2))\n",
        "ax.text(7, 5, '🎯\\nOrchestrator\\nAgent', ha='center', va='center', fontsize=11, fontweight='bold', color='white')\n",
        "\n",
        "# SOUL.md\n",
        "ax.add_patch(plt.Rectangle((5.5, 7.5), 1.3, 1.2, color=c_soul, ec='black', lw=1.5))\n",
        "ax.text(6.15, 8.1, 'SOUL.md', ha='center', va='center', fontsize=9, fontweight='bold')\n",
        "\n",
        "# MEMORY.md\n",
        "ax.add_patch(plt.Rectangle((7.2, 7.5), 1.3, 1.2, color=c_soul, ec='black', lw=1.5))\n",
        "ax.text(7.85, 8.1, 'MEMORY.md', ha='center', va='center', fontsize=9, fontweight='bold')\n",
        "\n",
        "# SubAgents\n",
        "sub_positions = [(10.5, 7.5), (10.5, 5), (10.5, 2.5)]\n",
        "sub_labels = ['📊 DataAgent\\n(isolated)', '📝 ReportAgent\\n(fork)', '⚠️ AlertAgent\\n(isolated)']\n",
        "for (x, y), label in zip(sub_positions, sub_labels):\n",
        "    ax.add_patch(plt.Rectangle((x-0.6, y-0.6), 1.8, 1.2, color=c_sub, alpha=0.8, ec='black', lw=1.5))\n",
        "    ax.text(x+0.3, y, label, ha='center', va='center', fontsize=8)\n",
        "\n",
        "# Tools\n",
        "tool_positions = [(10.5, 0.8), (12.5, 0.8)]\n",
        "tool_labels = ['🔧 query_shop', '🔧 send_notify']\n",
        "for (x, y), label in zip(tool_positions, tool_labels):\n",
        "    ax.add_patch(plt.Rectangle((x-0.3, y-0.3), 1.8, 0.6, color=c_tool, ec='black', lw=1))\n",
        "    ax.text(x+0.6, y, label, ha='center', va='center', fontsize=7)\n",
        "\n",
        "# 箭头\n",
        "ax.annotate('', xy=(5.5, 5), xytext=(2.8, 5), arrowprops=dict(arrowstyle='->', lw=2, color='black'))\n",
        "ax.annotate('', xy=(7, 7.5), xytext=(7, 6.5), arrowprops=dict(arrowstyle='->', lw=1.5, color='gray'))\n",
        "ax.annotate('', xy=(9.9, 7.5), xytext=(8.5, 5.5), arrowprops=dict(arrowstyle='->', lw=1.5, color='black'))\n",
        "ax.annotate('', xy=(9.9, 5), xytext=(8.5, 5), arrowprops=dict(arrowstyle='->', lw=1.5, color='black'))\n",
        "ax.annotate('', xy=(9.9, 2.5), xytext=(8.5, 4.5), arrowprops=dict(arrowstyle='->', lw=1.5, color='black'))\n",
        "\n",
        "# 审计日志\n",
        "ax.add_patch(plt.Rectangle((3, 0.5), 3, 1.5, color='#FFF3CD', ec='black', lw=1.5))\n",
        "ax.text(4.5, 1.25, '📋 审计日志\\nAudit Trail', ha='center', va='center', fontsize=9)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.savefig('/root/learning-notebooks/第7周/agent_architecture_day6.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "print('✅ 架构图已保存')"
    ]
})

# Cell 17: TaskFlow
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 🔄 Step 6：TaskFlow — 可追踪的多步工作流\n",
        "\n",
        "> 对于复杂任务（超过3步），用TaskFlow管理状态和等待\n",
        "\n",
        "## TaskFlow vs 简单工具链\n",
        "\n",
        "| 特性 | 简单工具链 | TaskFlow |\n",
        "|------|-----------|----------|\n",
        "| 步骤数 | 1-3步 | 4+步 |\n",
        "| 状态管理 | 无 | 持久化 |\n",
        "| 错误恢复 | 从头重来 | 从断点恢复 |\n",
        "| 人工介入 | 不支持 | 支持人审节点 |\n",
        "| 典型场景 | 查询商铺 | 月度经营报告生成 |\n",
        "\n",
        "### 💡 OpenClaw TaskFlow\n",
        "```python\n",
        "# TaskFlow典型流程\n",
        "task = TaskFlow()\n",
        "task.step(\"collect_data\")    # 收集数据\n",
        "task.step(\"analyze\")         # 分析趋势\n",
        "task.wait(\"human_review\")    # 等待人审\n",
        "task.step(\"generate_report\") # 生成报告\n",
        "task.step(\"send_notification\")# 推送通知\n",
        "```"
    ]
})

# Cell 18: TaskFlow code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Step 6: TaskFlow模拟实现\n",
        "\n",
        "class TaskFlow:\n",
        "    \"\"\"简化的TaskFlow实现\"\"\"\n",
        "    def __init__(self, name):\n",
        "        self.name = name\n",
        "        self.steps = []\n",
        "        self.results = {}\n",
        "        self.status = \"pending\"\n",
        "\n",
        "    def add_step(self, step_name, handler, depends_on=None, wait_for=None):\n",
        "        self.steps.append({\n",
        "            \"name\": step_name,\n",
        "            \"handler\": handler,\n",
        "            \"depends_on\": depends_on or [],\n",
        "            \"wait_for\": wait_for or [],\n",
        "            \"status\": \"pending\"\n",
        "        })\n",
        "\n",
        "    def run(self):\n",
        "        print(f'\\n🔄 TaskFlow: {self.name}')\n",
        "        print(f'   步骤数: {len(self.steps)}')\n",
        "        print(f'   状态: running\\n')\n",
        "        self.status = \"running\"\n",
        "\n",
        "        for step in self.steps:\n",
        "            # 检查依赖\n",
        "            skip = False\n",
        "            for dep in step[\"depends_on\"]:\n",
        "                if self.results.get(dep, {}).get(\"status\") != \"success\":\n",
        "                    print(f'  ⏭️ 跳过 {step[\"name\"]}（依赖 {dep} 未完成）')\n",
        "                    skip = True\n",
        "                    break\n",
        "            if skip:\n",
        "                continue\n",
        "\n",
        "            # 检查等待\n",
        "            if step[\"wait_for\"]:\n",
        "                print(f'  ⏸️ {step[\"name\"]} 等待人工审核...')\n",
        "                input_result = {\"approved\": True, \"reviewer\": \"Jason\"}\n",
        "                step[\"review\"] = input_result\n",
        "                print(f'     ✅ 审核通过（{input_result[\"reviewer\"]}）')\n",
        "\n",
        "            # 执行\n",
        "            print(f'  ▶️ 执行: {step[\"name\"]}')\n",
        "            try:\n",
        "                result = step[\"handler\"](self.results)\n",
        "                step[\"status\"] = \"success\"\n",
        "                self.results[step[\"name\"]] = {\"status\": \"success\", \"data\": result}\n",
        "                print(f'     ✅ 完成')\n",
        "            except Exception as e:\n",
        "                step[\"status\"] = \"failed\"\n",
        "                self.results[step[\"name\"]] = {\"status\": \"failed\", \"error\": str(e)}\n",
        "                print(f'     ❌ 失败: {e}')\n",
        "\n",
        "        self.status = \"completed\"\n",
        "        print(f'\\n✅ TaskFlow完成!')\n",
        "        return self.results\n",
        "\n",
        "\n",
        "# 定义一个月度报告TaskFlow\n",
        "def collect_data(prev):\n",
        "    return {\"shops\": 285, \"occupied\": 241, \"revenue\": 2850000}\n",
        "\n",
        "def analyze(prev):\n",
        "    data = prev.get(\"collect_data\", {}).get(\"data\", {})\n",
        "    occ_rate = data.get(\"occupied\", 0) / data.get(\"shops\", 1) * 100\n",
        "    return {\"occupancy_rate\": f\"{occ_rate:.1f}%\", \"revenue\": data.get(\"revenue\")}\n",
        "\n",
        "def generate_report(prev):\n",
        "    analysis = prev.get(\"analyze\", {}).get(\"data\", {})\n",
        "    return f\"月度经营报告: 出租率{analysis.get('occupancy_rate')}, 总收入¥{analysis.get('revenue'):,}\"\n",
        "\n",
        "def send_notification(prev):\n",
        "    report = prev.get(\"generate_report\", {}).get(\"data\", \"\")\n",
        "    return execute_tool(\"send_notification\", {\n",
        "        \"channel\": \"wechat\",\n",
        "        \"recipient\": \"Jason\",\n",
        "        \"message\": report[:80],\n",
        "        \"priority\": \"medium\"\n",
        "    })\n",
        "\n",
        "\n",
        "# 构建并运行TaskFlow\n",
        "tf = TaskFlow(\"月度经营报告生成\")\n",
        "tf.add_step(\"collect_data\", collect_data)\n",
        "tf.add_step(\"analyze\", analyze, depends_on=[\"collect_data\"])\n",
        "tf.add_step(\"human_review\", lambda prev: {\"approved\": True}, depends_on=[\"analyze\"], wait_for=[\"human\"])\n",
        "tf.add_step(\"generate_report\", generate_report, depends_on=[\"human_review\"])\n",
        "tf.add_step(\"send_notification\", send_notification, depends_on=[\"generate_report\"])\n",
        "\n",
        "results = tf.run()\n",
        "\n",
        "print(f'\\n📊 最终报告:')\n",
        "print(results.get(\"generate_report\", {}).get(\"data\", \"无\"))"
    ]
})

# Cell 19: Test
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "# ✏️ 课堂练习\n",
        "\n",
        "## 练习1：扩展工具\n",
        "\n",
        "在TOOL_REGISTRY中添加一个新工具 `query_foot_traffic`（查询客流量），\n",
        "参数包含 `shop_id`、`date_range`、`granularity`（小时/天/月）。\n",
        "\n",
        "<details>\n",
        "<summary>💡 参考答案</summary>\n",
        "\n",
        "```python\n",
        "TOOL_REGISTRY[\"query_foot_traffic\"] = {\n",
        "    \"description\": \"查询指定商铺的客流量数据\",\n",
        "    \"parameters\": {\n",
        "        \"type\": \"object\",\n",
        "        \"properties\": {\n",
        "            \"shop_id\": {\"type\": \"string\", \"description\": \"商铺编号\"},\n",
        "            \"date_range\": {\"type\": \"string\", \"description\": \"日期范围\"},\n",
        "            \"granularity\": {\"type\": \"string\", \"enum\": [\"hour\", \"day\", \"month\"]}\n",
        "        }\n",
        "    },\n",
        "    \"required\": [\"shop_id\", \"date_range\"],\n",
        "    \"permissions\": [\"read:traffic\"],\n",
        "    \"timeout_ms\": 5000\n",
        "}\n",
        "```\n",
        "</details>\n",
        "\n",
        "## 练习2：设计客服数字员工\n",
        "\n",
        "为一个购物中心设计一个「客服数字员工」，\n",
        "写出它的 SOUL.md 四层结构（Identity/Rules/Constraints/Output）。\n",
        "\n",
        "<details>\n",
        "<summary>💡 思考方向</summary>\n",
        "\n",
        "- Identity: 购物中心客服助手，面向顾客\n",
        "- Rules: 常见问题优先KB查询，投诉转人工，导航给路线图\n",
        "- Constraints: 不透露内部运营数据，不评论竞品\n",
        "- Output: 简洁友好，带emoji，路线用文字+图片\n",
        "</details>"
    ]
})

# Cell 20: 课后测试
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "# 📝 课后测试\n",
        "\n",
        "**Q1**: 数字员工的 SOUL.md 四层结构是哪四层？\n",
        "\n",
        "<details><summary>答案</summary>\n",
        "Identity（身份）→ Rules（规则）→ Constraints（约束）→ Output Format（输出格式）\n",
        "</details>\n",
        "\n",
        "**Q2**: 子Agent的 `isolated` 和 `fork` 上下文模式有什么区别？\n",
        "\n",
        "<details><summary>答案</summary>\n",
        "- isolated: 子Agent获得干净上下文，适合独立任务（如数据查询）<br>\n",
        "- fork: 继承父Agent的对话历史，适合需要上下文的连续任务（如报告生成）\n",
        "</details>\n",
        "\n",
        "**Q3**: TaskFlow比简单工具链多了什么能力？\n",
        "\n",
        "<details><summary>答案</summary>\n",
        "状态持久化、从断点恢复、支持人工审核节点、依赖管理\n",
        "</details>\n",
        "\n",
        "**Q4**: 为什么企业级数字员工必须有审计日志（Audit Trail）？\n",
        "\n",
        "<details><summary>答案</summary>\n",
        "因为Agent输出是概率性的（非确定性），必须记录「谁、何时、做了什么、结果如何」\n",
        "以便追溯责任、排查异常、满足合规要求。\n",
        "</details>\n",
        "\n",
        "**Q5**: 在今天的架构中，OrchestratorAgent的三个核心职责是什么？\n",
        "\n",
        "<details><summary>答案</summary>\n",
        "1. 意图识别与路由  2. 子Agent编排与调度  3. 结果整合与审计记录\n",
        "</details>"
    ]
})

# Cell 21: English Terms
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "# 🔑 英文术语（10个）\n",
        "\n",
        "| 术语 | 音标 | 释义 |\n",
        "|------|------|------|\n",
        "| **Orchestrator** | /ˈɔːkɪstreɪtər/ | 编排器，统一入口和路由 |\n",
        "| **Subagent** | /sʌbˈeɪdʒənt/ | 子代理，被主Agent调度的专业Agent |\n",
        "| **Audit Trail** | /ˈɔːdɪt treɪl/ | 审计轨迹，完整操作记录链 |\n",
        "| **Context Mode** | /ˈkɒntekst moʊd/ | 上下文模式（isolated/fork） |\n",
        "| **TaskFlow** | /tæsk floʊ/ | 任务流，多步骤可追踪工作流 |\n",
        "| **Tool Registry** | /tuːl ˈredʒɪstri/ | 工具注册表，管理所有可用工具的元数据 |\n",
        "| **Intent Classification** | /ɪnˈtent ˌklæsɪfɪˈkeɪʃən/ | 意图分类/识别 |\n",
        "| **Human-in-the-Loop** | /ˈhjuːmən ðə luːp/ | 人工介入环节，如审核节点 |\n",
        "| **Idempotency** | /ˌaɪdəmˈpoʊtənsi/ | 幂等性，重复调用不产生副作用 |\n",
        "| **Fallback** | /ˈfɔːlbæk/ | 降级方案，主方案失败时的备用路径 |"
    ]
})

# Cell 22: Resources
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "# 🎬 推荐学习资源\n",
        "\n",
        "## 📹 视频推荐\n",
        "\n",
        "1. **B站：2025最新版大模型AI Agent入门到精通实战教程**\n",
        "   - 链接：https://www.bilibili.com/video/BV1SqKHeUEm5/\n",
        "   - 简介：99集完整教程，涵盖Agent+RAG+LangGraph，从入门到项目实战\n",
        "\n",
        "2. **B站：2025必会的Agent课程（应用解读+项目实战）**\n",
        "   - 链接：https://www.bilibili.com/video/BV1LhgSzrEgr/\n",
        "   - 简介：20分钟搞懂AI Agent核心概念，72集系列覆盖应用场景和实战\n",
        "\n",
        "## 📖 延伸阅读\n",
        "\n",
        "1. **知乎：如何写好Agent的System Prompt?看这一篇就够了**\n",
        "   - 链接：https://zhuanlan.zhihu.com/p/1990950758582088647\n",
        "   - 简介：系统讲解System Prompt的结构化设计方法，含实战案例\n",
        "\n",
        "2. **CSDN：AI Agent开发实战：30分钟搭建AI数字员工**\n",
        "   - 链接：https://blog.csdn.net/weixin_43107715/article/details/157910358\n",
        "   - 简介：基于LangChain+LLM快速搭建数字员工，涵盖感知-规划-执行-记忆四大模块"
    ]
})

# Cell 23: Summary
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "# 📊 今日总结\n",
        "\n",
        "## ⚡ 实战成果\n",
        "\n",
        "今天我们从零搭建了一个完整的商管数字员工原型，整合了本周Day1-5所有知识：\n",
        "\n",
        "| 组件 | 来源 | 实现方式 |\n",
        "|------|------|----------|\n",
        "| SOUL.md | Day1 | 定义身份、规则、约束、输出格式 |\n",
        "| MEMORY.md | Day2 | 用户偏好 + 决策记录 + 语义搜索模拟 |\n",
        "| Tool Registry | Day3 | 商铺查询 + 租赁查询 + 通知发送 |\n",
        "| SubAgent | Day4 | DataAgent + ReportAgent + AlertAgent |\n",
        "| Audit Log | Day5 | 完整操作记录，支持追溯 |\n",
        "\n",
        "## 🎯 关键收获\n",
        "\n",
        "1. **数字员工 = 身份 + 记忆 + 工具 + 协作 + 监控**\n",
        "2. **Orchestrator是核心**：意图识别 → 路由 → 编排 → 整合\n",
        "3. **isolated vs fork**：独立任务用isolated，需要上下文用fork\n",
        "4. **TaskFlow解决复杂流程**：状态持久化 + 断点恢复 + 人工审核\n",
        "5. **审计日志是底线**：Agent的每一步都要可追溯\n",
        "\n",
        "## 🔮 与LangChat/OpenClaw的映射\n",
        "\n",
        "```\n",
        "本notebook的概念      →  LangChat/OpenClaw中的对应\n",
        "──────────────────────────────────────────────\n",
        "SOUL.md               →  OpenClaw的System Prompt + AGENTS.md\n",
        "MEMORY.md             →  OpenClaw的memory/*.md + memory_search\n",
        "Tool Registry         →  MCP Tool定义 + Capability Registry\n",
        "SubAgent              →  sessions_spawn (isolated/fork)\n",
        "TaskFlow              →  OpenClaw TaskFlow skill\n",
        "Audit Log             →  Orchestrator的trace/audit/metrics\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "## 📅 明天预告\n",
        "\n",
        "> **Day 7（周日）：🔄 W7全面复习**\n",
        "> 回顾Day1-6所有知识，做一套综合测试，查漏补缺！\n",
        "\n",
        "加油 Jason！💪🚀"
    ]
})

# Assemble notebook
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0"
        }
    },
    "cells": cells
}

output_path = "/root/learning-notebooks/第7周/第7周-Day6-实战搭建完整数字员工原型.ipynb"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"✅ Notebook generated: {output_path}")
print(f"   Cells: {len(cells)}")
print(f"   Size: {len(json.dumps(nb, ensure_ascii=False))} bytes")
